/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    colors: {
      transparent: "transparent",
      current: "currentColor",
      white: "#FFFFFF",
      primary: {
        900: "var(--primary-900)",
        700: "var(--primary-700)",
        500: "var(--primary-500)",
        300: "var(--primary-300)",
        100: "var(--primary-100)",
        50: "var(--primary-50)",
        DEFAULT: "var(--primary)",
        foreground: "var(--primary-foreground)",
      },
      accent: {
        900: "var(--accent-900)",
        700: "var(--accent-700)",
        500: "var(--accent-500)",
        300: "var(--accent-300)",
        100: "var(--accent-100)",
        DEFAULT: "var(--accent)",
        foreground: "var(--accent-foreground)",
      },
      secondary: {
        DEFAULT: "var(--secondary)",
        foreground: "var(--secondary-foreground)",
      },
      muted: {
        DEFAULT: "var(--muted)",
        foreground: "var(--muted-foreground)",
      },
      card: {
        DEFAULT: "var(--card)",
        foreground: "var(--card-foreground)",
      },
      background: "var(--background)",
      foreground: "var(--foreground)",
      border: "var(--border)",
      input: "var(--input)",
      ring: "var(--ring)",
    },
    spacing: {
      0: "0px",
      micro: "4px",
      xs: "8px",
      s: "16px",
      m: "24px",
      l: "32px",
      xl: "48px",
      "2xl": "64px",
      "3xl": "80px",
      "4xl": "120px",
      "5xl": "160px",
      "container-mobile": "24px",
      "container-tablet": "40px",
      "container-desktop": "80px",
    },
    fontSize: {
      h1: ["clamp(2.75rem, 2rem + 4vw, 7.875rem)", { lineHeight: "1.08", letterSpacing: "0.02em", fontWeight: "700" }],
      h2: ["clamp(2.125rem, 1.5rem + 3.2vw, 5rem)", { lineHeight: "1.35", letterSpacing: "-0.02em", fontWeight: "700" }],
      h3: ["clamp(1.75rem, 1.4rem + 1.8vw, 3rem)", { lineHeight: "0.9167", letterSpacing: "-0.01em", fontWeight: "600" }],
      h4: ["clamp(1.25rem, 1.1rem + 0.7vw, 1.5rem)", { lineHeight: "1.333", letterSpacing: "0em", fontWeight: "600" }],
      quote: ["2.25rem", { lineHeight: "1.333", letterSpacing: "-0.01em", fontWeight: "500" }],
      "body-lg": ["1.375rem", { lineHeight: "1.545", letterSpacing: "0em", fontWeight: "400" }],
      "body-lg-bold": ["1.375rem", { lineHeight: "1.545", letterSpacing: "0em", fontWeight: "700" }],
      body: ["1.125rem", { lineHeight: "1.667", letterSpacing: "0em", fontWeight: "400" }],
      "body-bold": ["1.125rem", { lineHeight: "1.667", letterSpacing: "0em", fontWeight: "700" }],
      caption: ["1rem", { lineHeight: "1.5", letterSpacing: "0em", fontWeight: "400" }],
      overline: ["1rem", { lineHeight: "1.375", letterSpacing: "0.10em", fontWeight: "600" }],
    },
    extend: {
      fontFamily: {
        heading: ['"Bricolage Grotesque"', "sans-serif"],
        body: ["Manrope", "sans-serif"],
      },
      maxWidth: { container: "1200px" },
      backgroundImage: {
        "accent-gradient": "linear-gradient(135deg, var(--accent-700), var(--accent-300))",
        "accent-gradient-light": "linear-gradient(135deg, var(--accent-100), var(--accent-50))",
      },
      gridTemplateColumns: { 12: "repeat(12, minmax(0, 1fr))" },
      gap: { gutter: "24px" },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
}
