export const copy = {
  pl: {
    h1: "Szyldowe Rewolucje.",
    h1Accent: "Strona konkursu dla projektantów.",
    body: <>Projekt koncepcyjny strony internetowej dla konkursu <strong className="text-slate-700">Szyldowe Rewolucje</strong>, inicjatywy walczącej z chaosem reklamowym w przestrzeni publicznej. Konkurs angażuje projektantów do tworzenia estetycznych, zgodnych z prawem szyldów dla lokalnych przedsiębiorców, a zwycięskie prace są realizowane w przestrzeni miejskiej. Projekt powstał w ramach studiów podyplomowych <strong className="text-slate-700">UX design | web analytics</strong> na Politechnice Białostockiej.</>,
    roleLabel: "Moja rola",
    roleText: "Research, wywiady z użytkownikami, analiza, prototypowanie, wireframes, testy użyteczności. Projekt powstał w ramach studiów podyplomowych UX design | web analytics na Politechnice Białostockiej.",
    chapters: {
      hero: "Start",
      s01: "Problem",
      s02: "Rozwiązanie",
      s03: "Odkrycia",
      s04: "Proces",
      s05: "Design",
      s06: "Wnioski",
    },
    meta: [
      { label: "Produkt", value: "Szyldowe Rewolucje" },
      { label: "Typ", value: "Konkurs dla projektantów" },
      { label: "Narzędzia", value: "Adobe XD · Miro" },
      { label: "Zakres", value: "UI/UX · Web concept" },
    ],
    s01: {
      h2: "Choroba bannerowa w przestrzeni miejskiej",
      p1: "Nielegalne i nieestetyczne reklamy zaśmiecają przestrzeń publiczną polskich miast. Samorządy walczą z tym zjawiskiem, ale zadanie jest trudne: wymaga podnoszenia świadomości mieszkańców i przedsiębiorców oraz wiąże się ze znacznymi kosztami.",
      p2: "Pytanie projektowe: jak zachęcić lokalną społeczność (mieszkańców, przedsiębiorców, samorządy) do dbania o estetykę przestrzeni miejskiej i ułatwić proces zmiany otoczenia, w którym żyjemy?",
    },
    s02: {
      h2: "Szyldowe Rewolucje",
      p1: "Konkurs dla projektantów, który ma realny wpływ na wizualną zmianę przestrzeni miejskiej. Organizowany jest przy wsparciu samorządów, które uchwaliły już uchwałę krajobrazową w swoich miastach. Zwycięski projekt nie ląduje w szufladzie, lecz jest realizowany w przestrzeni miejskiej.",
      p2: "Dzięki temu projektanci, oprócz nagrody pieniężnej, mają wpływ na walkę z chorobą bannerową, a lokalni przedsiębiorcy otrzymują profesjonalne, zgodne z wymogami prawa, reklamy przestrzenne.",
      p3: "Projekt obejmuje przygotowanie strony internetowej konkursu.",
    },
    s03: {
      h2: "Co pokazały badania",
      p1: "Na początku starałyśmy się zrozumieć rzeczywisty problem stojący za bannerami. W tym celu przeprowadziłyśmy desk research i stworzyłyśmy w zespole listę pytań badawczych.",
      p2: "Zdecydowałyśmy się przeprowadzić ankietę wśród mieszkańców miast (wszystkich grup wiekowych), aby poznać ich opinie. Żeby zebrać zdanie możliwie dużej grupy, zorganizowałyśmy badania ilościowe.",
      questionsLabel: "Pytania badawcze",
      questions: [
        "Jaki jest rzeczywisty problem z reklamami miejskimi?",
        "Jak duża jest świadomość społeczna? Co ludzie myślą o tym problemie?",
        "Kto i w jaki sposób podejmuje działania w celu rozwiązania problemu?",
        "Czy ktoś próbował już rozwiązać ten problem? Jakie były efekty?",
        "Czy informacje na bannerach są użyteczne?",
        "Gdzie reklamy są szczególnie uciążliwe?",
      ],
      insightsH3: "Kluczowe insighty",
      insights: [
        { title: "Brak wiedzy o prawie krajobrazowym", desc: "Większość nie wie, że takie przepisy istnieją." },
        { title: "Problem ze zrozumieniem prawa", desc: "Ustawa jest zbyt skomplikowana do samodzielnej interpretacji." },
        { title: "Niska świadomość problemu", desc: "Chaos reklamowy traktowany jest jako norma, nie problem." },
        { title: "Brak zaangażowania", desc: "Świadomość problemu rzadko przekłada się na działanie." },
        { title: "Potrzeba wiarygodnego źródła", desc: "Inicjatywa musi być poparta autorytetem, np. Urzędu Miasta." },
        { title: "Potrzeba ilustrowanego przewodnika", desc: "Prosty, wizualny poradnik z wymogami prawnymi, to czego brakuje." },
      ],
      personaH3: "Persona",
      personaDesc: "Na podstawie zebranych danych stworzyliśmy personę, żeby nie zapominać dla kogo projektujemy w trakcie całego procesu.",
    },
    s04: {
      h2: "Od architektury informacji po wireframes",
      p: "Na podstawie badań zaprojektowałyśmy architekturę informacji serwisu: stronę główną, sekcję o konkursie, informator, galerię poprzednich edycji i formularz zgłoszeniowy. W pierwszej iteracji powstały low-fi wireframes, które pozwoliły zweryfikować założenia i wychwycić braki przed przejściem do high fidelity.",
    },
    s05: {
      h2: "Low fidelity wireframes i High fidelity mockup",
      lofiH3: "Low fidelity wireframes",
      lofiP: "W pierwszej iteracji stworzyłyśmy low-fi wireframes, żeby sprawdzić czy nasze założenia są możliwe do zrealizowania oraz wychwycić braki i elementy zbędne zanim przeszłyśmy do właściwego projektu.",
      hifiH3: "High fidelity mockup",
      hifiP: "Finalny design oparłyśmy na żółto-czarnej palecie barw nawiązującej do sygnalizacji i oznaczeń miejskich. Celem było stworzenie strony czytelnej, minimalistycznej i dostępnej, zarówno na desktopie, jak i na urządzeniach mobilnych. Projekt uwzględnia stronę główną, informator o przepisach, galerię edycji, formularz zgłoszeniowy i ekran potwierdzenia.",
    },
    s06: {
      h2: "Co bym zrobiła inaczej",
      intro: "Testy użyteczności były dla mnie najbardziej wartościowym momentem projektu: obserwowanie jak prawdziwi użytkownicy wchodzą w interakcję z produktem weryfikuje założenia, które wydają się oczywiste w trakcie projektowania.",
      items: [
        { title: "Dostępność to fundament, nie opcja", desc: "Wchodząc w projekt skupiałam się na estetyce i strukturze, a dostępność traktowałam jako późniejszy krok. Testy pokazały, że kontrast i wyrównanie tekstu realnie blokują użytkowników, nie tylko z niepełnosprawnościami. Następnym razem zaczynam od dostępności." },
        { title: "Język projektanta ≠ język użytkownika", desc: "Terminy, które dla mnie były oczywiste, użytkownicy interpretowali różnie. Nauczyłam się, że każdy komunikat wymaga testu, szczególnie w formularzach i procesach wielokrokowych." },
        { title: "Hierarchia informacji ważniejsza niż kompletność", desc: "Chciałam pokazać wszystko. Użytkownicy chcieli znaleźć jedno konkretne. Nauczyłam się projektować pod pytanie 'co użytkownik chce zobaczyć najpierw', nie 'co chcę mu pokazać'." },
      ],
    },
  },
  en: {
    h1: "Banner Revolution.",
    h1Accent: "Competition website for designers.",
    body: <>A conceptual website project for the <strong className="text-slate-700">Szyldowe Rewolucje</strong> competition, an initiative fighting advertising chaos in public space. The competition engages designers to create aesthetic, legally compliant signage for local businesses, with winning designs realized in urban space. The project was created as part of postgraduate studies in <strong className="text-slate-700">UX design | web analytics</strong> at the Białystok University of Technology.</>,
    roleLabel: "My role",
    roleText: "Research, user interviews, analysis, prototyping, wireframes, usability tests. Project created as part of postgraduate studies in UX design | web analytics at Białystok University of Technology.",
    chapters: {
      hero: "Start",
      s01: "Problem",
      s02: "Solution",
      s03: "Discovery",
      s04: "Process",
      s05: "Design",
      s06: "Takeaways",
    },
    meta: [
      { label: "Product", value: "Szyldowe Rewolucje" },
      { label: "Type", value: "Designer competition" },
      { label: "Tools", value: "Adobe XD · Miro" },
      { label: "Scope", value: "UI/UX · Web concept" },
    ],
    s01: {
      h2: "Banner disease in urban space",
      p1: "Illegal and unaesthetic advertising pollutes public spaces in Polish cities. Local governments fight this, but the task is difficult: it requires raising awareness among residents and businesses, and involves significant costs.",
      p2: "Design question: how to encourage the local community (residents, businesses, local governments) to care about the aesthetics of urban space and make it easier to change the environment we live in?",
    },
    s02: {
      h2: "Szyldowe Rewolucje",
      p1: "A competition for designers with a real impact on the visual change of urban space. Organized with the support of local governments that have already adopted a landscape resolution. The winning design isn't shelved, it's realized in urban space.",
      p2: "This gives designers a cash prize plus real impact on fighting banner disease, while local businesses receive professional, legally compliant outdoor advertising.",
      p3: "The project includes designing the competition website.",
    },
    s03: {
      h2: "What the research revealed",
      p1: "First, we tried to understand the real problem behind the banners. We conducted desk research and created a list of research questions as a team.",
      p2: "We decided to survey city residents (all age groups) to gather their opinions. To reach as large a group as possible, we ran quantitative research.",
      questionsLabel: "Research questions",
      questions: [
        "What is the real problem with urban advertising?",
        "How widespread is social awareness? What do people think about this problem?",
        "Who takes action to solve the problem, and how?",
        "Has anyone already tried to solve this problem? What were the results?",
        "Are the messages on banners useful?",
        "Where are advertisements particularly problematic?",
      ],
      insightsH3: "Key insights",
      insights: [
        { title: "Lack of knowledge about landscape law", desc: "Most people don't know such regulations exist." },
        { title: "Difficulty understanding the law", desc: "The act is too complex to interpret independently." },
        { title: "Low problem awareness", desc: "Advertising chaos is treated as normal, not a problem." },
        { title: "Lack of engagement", desc: "Awareness of the problem rarely translates into action." },
        { title: "Need for a credible source", desc: "The initiative must be backed by authority, e.g. the City Office." },
        { title: "Need for an illustrated guide", desc: "A simple, visual guide with legal requirements, that's what's missing." },
      ],
      personaH3: "Persona",
      personaDesc: "Based on the data collected, we created a persona, to keep in mind who we're designing for throughout the process.",
    },
    s04: {
      h2: "From information architecture to wireframes",
      p: "Based on the research, we designed the site's information architecture: the homepage, competition section, guide, gallery of previous editions and submission form. In the first iteration, low-fi wireframes were created, allowing us to verify assumptions and catch gaps before moving to high fidelity.",
    },
    s05: {
      h2: "Low fidelity wireframes and High fidelity mockup",
      lofiH3: "Low fidelity wireframes",
      lofiP: "In the first iteration we created low-fi wireframes to check whether our assumptions were achievable and to catch gaps and redundant elements before moving to the actual design.",
      hifiH3: "High fidelity mockup",
      hifiP: "The final design was based on a yellow-black color palette referencing urban signage and markings. The goal was to create a readable, minimalist and accessible site, on both desktop and mobile. The design covers the homepage, legal requirements guide, edition gallery, submission form and confirmation screen.",
    },
    s06: {
      h2: "What I would do differently",
      intro: "Usability tests were the most valuable moment of the project: watching real users interact with the product verifies assumptions that seem obvious during design.",
      items: [
        { title: "Accessibility is foundational, not optional", desc: "Entering the project I focused on aesthetics and structure, treating accessibility as a later step. Tests showed that contrast and text alignment genuinely block users, not just those with disabilities. Next time, I start with accessibility." },
        { title: "Designer language ≠ user language", desc: "Terms that were obvious to me, users interpreted differently. I learned that every piece of communication needs testing, especially in forms and multi-step processes." },
        { title: "Information hierarchy over completeness", desc: "I wanted to show everything. Users wanted to find one specific thing. I learned to design around the question 'what does the user want to see first', not 'what do I want to show them'." },
      ],
    },
  },
}
