import { projectTags } from "@/data/projectTags"

export const copy = {
  pl: {
    heroEyebrow: "CASE STUDY - LOCALO · CLIENT ACQUISITION",
    heroTags: projectTags.clientAcquisition,
    heroTitle: "do pozyskiwania klientów.",
    heroTitleAccent: "Jeden flow",
    heroLead:
      "Generowanie leadów i research widoczności istniały w Localo osobno. Obydwa działały i praktycznie nikt nie uruchamiał ich sam – wartość docierała do ludzi dopiero na callu z Customer Success. Do tego jedno i drugie kończyło się w zewnętrznym CRM-ie albo w arkuszu. Zaprojektowałam Client Acquisition: jedno narzędzie z dwoma modułami, które tłumaczy się samo i domyka zadanie bez wychodzenia na zewnątrz. Po redesignie mediana sesji na funkcji wzrosła z 4,0 do 7,3 minuty, a liczba calli onboardingowych spadła.",
    metaBar: [
      { label: "PRODUKT", value: "Localo" },
      { label: "SKALA", value: "6 700+ użytkowników" },
      { label: "BRANŻA", value: "Local SEO / B2B SaaS" },
      { label: "UŻYTKOWNICY", value: "Freelancerzy, specjaliści SEO, agencje" },
    ],
    chapters: {
      skrot: "01 W skrócie",
      problem: "02 Wiedza",
      discovery: "03 Proces",
      handoff: "05 Handoff",
      rozwiazanie: "04 Rozwiązanie",
      wynik: "06 Wynik",
      podsumowanie: "07 Podsumowanie",
    },
    skrot: {
      eyebrow: "01 · KONTEKST, EFEKT I ROLA",
      title: "W skrócie",
      introBold: "Localo to narzędzie dla osób, które zarządzają wizytówkami Google",
      introRest:
        " — jedną albo kilkudziesięcioma naraz. Automatyzuje pracę i mówi, co zrobić dalej: lista zadań na tydzień z priorytetami dla każdej wizytówki, audyty w kilka sekund, raporty gotowe do wysłania klientowi w kilka minut.",
      contextPanel: {
        title: "Brief — Client Acquisition",
        text1: "Funkcja powstała w ramach MVP, zbudował ją dev i została taka, jaka była. Nikt w zespole nie udawał, że jest dobrze.",
        text2: "„Wiemy, że UX i generalnie projekt tej funkcji jest słaby – użytkownicy dopiero po onboardingu przez Customer Success, na callach, są w stanie zrozumieć wartość narzędzia i jakkolwiek z niego korzystać. Chcemy, żeby użytkownicy weszli, zobaczyli efekt wow i sami z tego korzystali.”",
      },
      closingLead: "To nie był projekt, w którym trzeba było odkryć problem. Problem był znany - ",
      closingBold: "Cała robota była w tym, jak to zrobić.",
      statsIntroTitle: "Jak zmieniły się metryki:",
      stats: [
        { value: "+81%", label: "dłuższa mediana sesji na funkcji: 4,0 → 7,3 min" },
        { value: "5,5x", label: "częściej płacą użytkownicy funkcji niż reszta bazy: 28,0% vs 5,1%" },
        { value: "~9x", label: "wyższe blended LTV użytkownika funkcji: $149,97 vs $16,31" },
      ],
      statsCaption: "Dwie ostatnie to porównanie użytkowników funkcji z resztą bazy, nie pomiar przed i po. Rozbieram to w rozdziale 07.",
      roleOverline: "MOJA ROLA — DESIGN LEAD OD A DO Z",
      roleQuote: "W Localo odpowiadałam za cały produkt – od discovery po delivery.",
      roleList: [
        "definiowałam problemy",
        "prowadziłam badania i projektowałam UI/UX",
        "testowałam z użytkownikami i iterowałam",
        "doradzałam, co wchodzi na roadmapę, a co nie",
        "rozwijałam design system i utrzymywałam go wspólnie z devami",
        "chodziłam na rozmowy z klientami, żeby nie opierać się na cudzych notatkach",
        "mentorowałam młodszą projektantkę",
      ],
      scopePanel: {
        title: "Redesign: Research & Sales mode",
        blocks: [
          { label: "MÓJ ZAKRES", text: "audyt ekspercki istniejącej funkcji, nowa architektura informacji, user journey i flow użytkownika, nazewnictwo, UI, stany i komunikaty, handoff, design QA." },
          { label: "WSPÓŁPRACA", text: "zakres i priorytety. Zespół developerski – ograniczenia techniczne, od początku. Customer Success – wiedza o tym, czego ludzie nie rozumieli na callach. Do tego wsparcie QA i writera." },
        ],
      },
    },
    problem: {
      eyebrow: "02 · Zbieranie wiedzy",
      title: "Wiedza była w zespole",
      introPre: "Client Acquisition trafiał do ludzi, ",
      introBold: "których zachowania zgłębiałam już wcześniej",
      introRest: ", przy innych projektach w Localo. Siadałam więc do tego z gotową personą i z wiedzą o tym, jak pracują na co dzień i jakie potrzeby mają.",
      persona: {
        overline: "KOGO DOTYCZY (PERSONA)",
        quote: "Freelancerzy, specjaliści SEO i osoby odpowiedzialne w agencji za pozyskiwanie klientów.",
        commonBold: "Wspólne dla nich: ",
        commonText: "nie przychodzą po dane, tylko po odpowiedź na pytanie do kogo mam jutro zadzwonić i co mu pokażę.",
      },
      sourcesTitle: "Źródła wiedzy i kluczowe odkrycia",
      sourcesIntro: "Zakres projektu nie przewidywał ponownego discovery ani głębszych badań. Oparłam się na czterech źródłach, które mówiły wprost o tej funkcji: własnym ",
      sourcesIntroBold: "audycie eksperckim, nagraniach sesji, zgłoszeniach do supportu i wiedzy Customer Success.",
      auditTitle: "Audyt ekspercki",
      auditItems: ["Doświadczenie", "10 Heurystyk Nielsena", "Wytyczne i najlepsze praktyki", "Dostępność"],
      moreSourcesLead: "Ponad to szukałam jeszcze informacji w tych miejscach:",
      sourceCards: [
        { title: "Nagrania sesji w Clarity", text: "Audyt mówi, co jest zepsute według zasad. Nagrania mówią, gdzie ludzie faktycznie się zatrzymują, co klikają i w którym momencie zamykają kartę." },
        { title: "Rozmowy z Customer Success", text: "Oni tłumaczyli tę funkcję na żywo dziesiątki razy, więc wiedzieli o niej rzeczy, których nie widać w interfejsie: co dokładnie opowiadają klientom, z czym użytkownicy mają największy problem i w którym momencie zapala im się światełko, że to ma sens." },
        { title: "Tickety supportu", text: "Przejrzałam zgłoszenia dotyczące funkcji: to jest lista frustracji, problemów czy potrzeba pomocy. Głównie wracały w nich pytania o kredyty – i to zgłoszenie wróciło potem jako konkretna zmiana w projekcie." },
        { title: "Sesja z developerami", text: "Wciągnęłam zespół developerski, zanim cokolwiek narysowałam. Chciałam wiedzieć, jak ta funkcja działa dziś i dlaczego tak, jakie mamy ograniczenia techniczne, co nas blokuje i z czego już wiadomo, że chcemy zrezygnować albo przenieść na inną technologię." },
      ],
      aiSynthesisTitle: "Synteza badań z AI",
      aiSynthesisText: "Połączyłam nagrania z Clarity, rozmowy z supportem i spostrzeżenia z audytu eksperckiego za pomocą Clauda. Chciałam zobaczyć gdzie spostrzeżenia się pokrywają, czy powstają wzorce oraz które odnotowane frustracje pojawiają się najczęściej.",
      findingsTitle: "Kluczowe odkrycia",
      findings: [
        { number: "01", title: "Wysoka bariera wejścia", text: "Każdy nowy użytkownik wymagał ręcznego onboardingu od CS. Użytkownik wchodząc do narzędzia, nie wiedział co dostanie." },
        { number: "02", title: "Wyniki nie były powtarzalne", text: "To samo zapytanie potrafiło zwrócić inną listę, a nie było jak wrócić do poprzedniej – bez snapshotów i bez historii wyszukiwań." },
        { number: "03", title: "Brak ciągłości", text: "Leady w Sales mode, dane o widoczności w Research, bez wspólnego kontekstu i bez widocznego połączenia między nim." },
        { number: "04", title: "Zewnętrzne narzędzia", text: "Jedno zadanie, kilka wyjść z narzędzia. Lead był wierszem bez danych do decyzji – brak strony, liczba opinii i link do map to były dopiero cele projektu – a statusy kontaktu i notatki mieszkały w cudzym arkuszu." },
        { number: "05", title: "Niewidoczny koszt", text: "Brak komunikacji limitów. Nigdzie nie było wiadomo, ile użytkownik ma kredytów, ile kosztuje akcja ani co się stanie, gdy się skończą." },
      ],
      scopeTitle: "Zakres, czyli co robimy, a czego nie",
      scopeIntro: "Z PM-em i zespołem ustaliłam dokładnie, co wchodzi w zakres redesignu. Weszły m.in.: ",
      scopeIntroBold: "stabilizacja generowania list, mikro-CRM ze statusami leadów, lepszy podgląd leada, komunikacja limitów, komunikacja wartości, nazewnictwo oraz widoczne połączenie między obiema częściami funkcji.",
      scopeIntroEnd: " Trzy rzeczy wykluczyliśmy świadomie:",
      scopeOut: [
        { title: "Sposób dodawania keywordów.", text: "Korzystaliśmy z niego w innych miejscach aplikacji, więc zmiana tutaj oznaczałaby przemyślenie go wszędzie. ", textBold: "Na to potrzeba było osobnego projektu." },
        { title: "Historia wyników.", text: "Zaczyna być coś warta dopiero wtedy, gdy ludzie wracają do funkcji. ", textBold: "Najpierw trzeba było sprawdzić, czy wrócą." },
        { title: "Dokupowanie kredytów.", text: "Paczki, przedziały cenowe, rozliczenie jednorazowe czy doliczane do abonamentu — to decyzja o modelu płatności i ", textBold: "wymaga rozmowy z biznesem." },
      ],
      scopeClosing1Pre: "Taka lista zrobiła dwie rzeczy: ",
      scopeClosing1Bold: "trzymała nas w ryzach",
      scopeClosing1Rest: " – kiedy odpływaliśmy z pomysłami, wracaliśmy do „umowy”, dzięki czemu nie zakopaliśmy się w jednym projekcie na pół roku. Wyrównała też oczekiwania: manager wiedział, jaki będzie output, a ja i devowie wiedzieliśmy, za co odpowiadamy.",
      scopeClosing2: "Zawsze też, i tym razem również, sformułowałam cel, który został przedstawiony i zatwierdzony przez zespół. Dzięki temu na każdym etapie projektu pamiętamy, dla kogo i po co to robimy.",
      goalOverline: "CEL",
      goalPre: "Zdjąć z zespołu obowiązek tłumaczenia funkcji. ",
      goalBold: "Użytkownik ma wejść, zobaczyć wynik i korzystać dalej sam",
      goalRest: " – bez calla, bez instrukcji, bez wychodzenia do zewnętrznych narzędzi.",
    },
    discovery: {
      eyebrow: "03 · Proces",
      title: "Najpierw ścieżka, potem ekrany",
      flow: {
        title: "Nowe flow, zanim powstał pierwszy ekran",
        text1: "Zmapowałam całą drogę użytkownika od nowa: od wyszukania firmy, przez ocenę leada i skan widoczności, po materiał do wysłania, status kontaktu i aktywację profilu. To nie było przerysowanie tego, co istniało – żaden z dwóch trybów nie prowadził przez całą tę drogę, więc trzeba było ją złożyć.",
        text2: "Mapa dała zespołowi wspólny obraz zakresu, wyciągnęła sytuacje brzegowe, zanim zdążyły stać się problemem projektowym, i ustawiła strukturę, na której stanęła potem cała funkcja.",
      },
      lowfiTitle: "Low-fi, zanim cokolwiek wyglądało",
      lowfiIntro: "Zanim powstały ładne makiety, zrobiłam draft i prototyp low-fi. Chciałam sprawdzić układ, ale przede wszystkim mieć pewność, że rozumiemy, jak ta funkcja działa dziś i jak chcemy, żeby działała. Przy funkcji zbudowanej wcześniej przez kogoś innego to nie jest oczywiste ani dla mnie, ani dla zespołu.",
      decisionsTitle: "Kluczowe decyzje",
      decision1: {
        title: "Jedno miejsce działania",
        rejectedLabel: "Odrzucony wariant:",
        rejectedPre: "zostawić Sales mode i Research mode ",
        rejectedBold: "osobno",
        rejectedRest: ", połączone nawigacją i onboardingiem. Logicznie czyste – jedno to analiza, drugie to sprzedaż.",
        reasonLabel: "Powód:",
        reasonText: "praca jest sekwencyjna – najpierw znajdź firmę, potem przygotuj dla niej materiał. Przejście z „o, potencjalny klient” do „wygeneruj mu mapę pozycji” ma być jednym ruchem, a granica między trybami przechodziła dokładnie tędy.",
      },
      namingCard: {
        title: "Nazwy mówią, co się stanie",
        text: "Sales mode i Research mode → Client Acquisition z dwoma modułami: Leads finder i Visibility scans. Stare nazwy opisywały tryb pracy narzędzia, nowe opisują, co użytkownik dostanie. Wygląda na kosmetykę i było jedną z najtańszych rzeczy, które podniosły zrozumiałość funkcji. Nazwa jest pierwszym tooltipem, jaki widzi użytkownik – i jedynym, którego nie da się pominąć.",
      },
      resultCard: {
        title: "Jeden wynik zamiast pięciu liczb",
        para1: "Leady dostają Growth Potential – jedną wartość, która przyspieszy filtrowanie potencjalnych klientów.",
        reasonLabel: "Powód:",
        para2: " surowe metryki przerzucały na użytkownika obliczenie „czy warto”, a to ",
        reasonBold: "wymaga wiedzy i czasu na analizę.",
        para3: " Surowe dane zostały, ale od teraz służyły tylko do pogłębionej analizy — wstępną robi Localo.",
      },
    },
    handoff: {
      eyebrow: "05 · Handoff i wdrożenie",
      title: "Handoff — co dostali devowie",
      introPre: "Devowie dostali makiety w Figmie ",
      introBold: "ułożone we flow",
      introRest: ": wszystkie stany, przykłady notyfikacji, wersje mobilne i adnotacje wdrożeniowe w miejscach, które wymagały decyzji. Do tego opis sytuacji brzegowych – co się dzieje, kiedy danych nie ma – tokeny z design systemu i klikalny prototyp, żeby dało się przejść całość przed napisaniem pierwszej linijki kodu.",
      intro2Pre: "Byłam z devami ",
      intro2Bold: "w kontakcie na bieżąco",
      intro2Rest: ", więc pytania rozstrzygały się od ręki. Sprawdzałam wdrożenie na środowisku testowym i zgłaszałam różnice względem projektu. Wspierałam QA przy definiowaniu tego, co trzeba sprawdzić, a po wdrożeniu zbierałam poprawki.",
      blurCaption: "Zamazane ze względu na bezpieczeństwo danych",
    },
    rozwiazanie: {
      eyebrow: "04 · Finalne rozwiązanie",
      title: "Od leada do klienta",
      intro: "Poniżej finalne rozwiązanie. Użytkownik wpisuje branżę i miasto, dostaje listę firm i wybiera tę, u której najłatwiej będzie pokazać efekt. Sprawdza jej widoczność, wysyła mapę pozycji pod własną marką, zapisuje, co ustalili przez telefon. Kiedy klient mówi tak — aktywuje mu wizytówkę. Wszystko w jednym narzędziu, od pierwszego wyszukiwania po pierwszy dzień współpracy.",
      leadsFinderTitle: "Leads Finder — wyszukiwanie potencjalnych klientów",
      b1: {
        title: "Osobna lista na każde wyszukiwanie",
        text: "Każdy projekt to lista leadów zebrana na jedno słowo kluczowe i jedną lokalizację — dentyści w Toruniu i fryzjerzy w Warszawie mogą lecieć równolegle. Status na karcie mówi, co jest w toku, co zamknięte, a co pochodzi jeszcze z poprzedniej wersji funkcji.",
      },
      b2: [
        { title: "Tag Legacy przy przeniesionych listach", text: "Starych danych nie dało się zaciągnąć do nowej struktury. Przeniesione listy dostają tag Legacy, żeby było wiadomo, że wynik może się nieco różnić od nowych." },
        { title: "Koszt widoczny przed kliknięciem", text: "Stan kredytów i cena akcji stoją w tym samym oknie, w którym użytkownik wpisuje słowo kluczowe i lokalizację. Limit przestał być niespodzianką, o którą trzeba pytać support." },
      ],
      b3: {
        title: "Użytkownik układa listę pod siebie",
        text: "Filtry i sortowanie zawężają listę do interesujących firm i ustawiają je w kolejności, w jakiej mają zostać obdzwonione.",
      },
      b4: [
        { title: "Growth Potential wskazuje najlepsze leady", text: "Jedna wartość mówi, jak łatwo będzie u danej firmy pokazać efekt. Im wyższa, tym szybciej widać rezultat — użytkownik sortuje listę i ma najlepsze leady na górze." },
        { title: "Dowód do rozmowy w jednym kliknięciu", text: "Zielone punkty to widoczność, czerwone jej brak, pomarańczowe słabą pozycję. Mapa pozycji generuje się z listy leadów i wysyła jako link bez logo Localo, pod marką agencji." },
      ],
      b5: [
        { title: "Miejsce na własne notatki", text: "Przy każdym leadzie użytkownik dopisuje to co przyda się przy następnej rozmowie. Nie potrzebuje do tego osobnych notatek per klient." },
        { title: "Status kontaktu przy każdym leadzie", text: "Użytkownik oznacza, na jakim etapie jest rozmowa z daną firmą, w tym samym widoku, w którym tę firmę znalazł. Arkusz prowadzony obok Localo przestał być potrzebny." },
      ],
      b6: {
        title: "Materiał sprzedażowy bez zajmowania slotu",
        text: "Kiedy rozmowa się toczy, użytkownik generuje kolejne mapy pozycji na kolejne słowa kluczowe. Płaci kredytami z planu, ale nie dodaje cudzej wizytówki do Localo i nie zajmuje slotu — profil zostaje w Client Acquisition, dopóki nie ma umowy.",
      },
      b7: {
        title: "Aktywacja nowej wizytówki",
        text: "Kiedy klient się zgadza, użytkownik aktywuje jego wizytówkę w Localo i zaczyna monitoring oraz optymalizację. Dopiero ten krok zajmuje slot w planie.",
      },
    },
    wynik: {
      eyebrow: "06 · Wyniki",
      title: "Co pokazały liczby",
      heroStat: { value: "+81%", label: "dłuższa mediana sesji na funkcji: z 4,0 do 7,3 minuty. Przy prospectingu dłużej znaczy lepiej. Kto siedzi w liście leadów siedem minut, ten zaczął jej używać." },
      sessionsStat: { value: "3 425 → 8 403", label: "Ilość sesji na funkcji" },
      smallStats: [
        { value: "5,5×", label: "Użytkownicy funkcji płacą częściej" },
        { value: "9x", label: "Wyższe blended LTV na użytkowniku funkcji" },
      ],
      dataCaption: "Okres: sierpień–listopad 2025 dla starej wersji, grudzień 2025–czerwiec 2026 dla nowej; przełączenie w grudniu 2025.",
      whatItMeansTitle: "Co za tymi liczbami stoi",
      para1Pre: "Cel z briefu domknął się poza danymi. Jak raportuje CS team - ",
      para1Bold: "liczba callów onboardingowych spadła",
      para1Rest: ", funkcja przestała być czymś, co musieli tłumaczyć na żywo.",
      para2Bold: "Funkcja rosła szybciej niż sama aplikacja",
      para2Rest: ". Baza poszła w tym czasie z 4,1 tys. do 6,7 tys. MAU, a udział funkcji w aktywnych użytkownikach mimo to podniósł się z ~7,3% do ~7,8%. Utrzymanie udziału przy bazie większej o dwie trzecie oznacza, że funkcja zdobywała nowych ludzi w tempie szybszym niż produkt.",
      para3Pre: "Ludzie zaczęli w funkcji zostawać. Mediana sesji wzrosła o 81%, liczba sesji o 145%, a zdarzeń na sesję przybyło minimalnie: 11,2 → 12,1. Nie klikają więcej – a jednak ",
      para3Bold: "spędzają tam więcej czasu",
      para3Rest: ". Przy pracy z listą leadów i mapą pozycji to jest dokładnie to, o co chodziło.",
      para4: "Funkcja trafiła w najbardziej wartościowy segment. Użytkownicy Client Acquisition płacą 5,5× częściej niż reszta bazy i mają około 9× wyższe blended LTV. To narzędzie dla freelancerów i agencji, czyli dla tych, którzy w Localo zostawiają najwięcej pieniędzy – i to im odpowiedziało na realną potrzebę.",
    },
    podsumowanie: {
      eyebrow: "07 · Wnioski",
      title: "Wykonanie, nie odkrywanie",
      intro: "To nie był klasyczny projekt: discovery, research, design, delivery. To jest przykład dobrze wykonanego powierzonego zadania. Ze spotkań wiedzieliśmy, że użytkownicy po wprowadzeniu ich w funkcję dostrzegali wartość i chętnie z niej korzystali. Moim zadaniem było sprawić, żeby robił to interfejs, a nie zespół.",
      lessons: [
        { title: "Głos developerów w projekcie jest ważny", text: "Wciągnęłam devów przed pierwszą makietą i to była najlepsza decyzja procesowa w tym projekcie. A i tak dane legacy wyszły w trakcie i trzeba je było rozwiązać projektowo – tagiem Legacy na karcie. Wcześniejsza rozmowa nie gwarantuje, że nic nie wyskoczy. Gwarantuje, że wyskoczy przy Tobie, a nie na produkcji." },
        { title: "Co bym zrobiła inaczej", text: "Testy przenieśliśmy na produkcję i przy jednej rzeczy zrobiłabym to inaczej: Growth Potential. To jedyne miejsce, w którym użytkownik oddaje decyzję algorytmowi, a algorytm poszedł do ludzi bez sprawdzenia, czy jego wynik zgadza się z ich intuicją." },
      ],
    },
  },
  en: {
    heroEyebrow: "CASE STUDY - LOCALO · CLIENT ACQUISITION",
    heroTags: projectTags.clientAcquisition,
    heroTitle: "for client acquisition.",
    heroTitleAccent: "One flow",
    heroLead:
      "Lead generation and visibility research existed in Localo separately. Both worked, but almost nobody launched them on their own — the value only reached people on a Customer Success call. On top of that, both ended up in an external CRM or a spreadsheet. I designed Client Acquisition: one tool with two modules that explains itself and closes the loop without leaving the product. After the redesign, median session time on the feature grew from 4.0 to 7.3 minutes, and the number of onboarding calls dropped.",
    metaBar: [
      { label: "PRODUCT", value: "Localo" },
      { label: "SCALE", value: "6,700+ users" },
      { label: "INDUSTRY", value: "Local SEO / B2B SaaS" },
      { label: "USERS", value: "Freelancers, SEO specialists, agencies" },
    ],
    chapters: {
      skrot: "01 Long story short",
      problem: "02 Knowledge",
      discovery: "03 Process",
      handoff: "05 Handoff",
      rozwiazanie: "04 Solution",
      wynik: "06 Results",
      podsumowanie: "07 Summary",
    },
    skrot: {
      eyebrow: "01 · CONTEXT, IMPACT & ROLE",
      title: "Long story short",
      introBold: "Localo is a tool for people managing Google Business Profiles",
      introRest:
        " — one or dozens at a time. It automates the work and tells you what to do next: a weekly task list with priorities for every profile, audits in seconds, reports ready to send to a client in minutes.",
      contextPanel: {
        title: "Brief — Client Acquisition",
        text1: "The feature was built as an MVP by a single developer and stayed exactly as it was. Nobody on the team pretended it was good.",
        text2: "“We know the UX and the overall design of this feature is weak — users only understand the tool's value, and how to use it at all, after onboarding with Customer Success on a call. We want users to come in, see the wow effect, and use it on their own.”",
      },
      closingLead: "This wasn't a project where the problem had to be discovered. The problem was known - ",
      closingBold: "the entire job was figuring out how to solve it.",
      statsIntroTitle: "How the metrics changed:",
      stats: [
        { value: "+81%", label: "longer median session on the feature: 4.0 → 7.3 min" },
        { value: "5.5x", label: "more likely to pay than the rest of the base: 28.0% vs 5.1%" },
        { value: "~9x", label: "higher blended LTV for feature users: $149.97 vs $16.31" },
      ],
      statsCaption: "The last two compare feature users against the rest of the base, not a before/after measurement. I break this down in chapter 07.",
      roleOverline: "MY ROLE — DESIGN LEAD, END TO END",
      roleQuote: "At Localo I owned the entire product — from discovery to delivery.",
      roleList: [
        "defined the problems",
        "led research and designed the UI/UX",
        "tested with users and iterated",
        "advised on what made the roadmap and what didn't",
        "grew the design system and maintained it together with engineering",
        "joined client calls, so I wasn't relying on someone else's notes",
        "mentored a junior product designer",
      ],
      scopePanel: {
        title: "Redesign: Research & Sales mode",
        blocks: [
          { label: "MY SCOPE", text: "expert audit of the existing feature, new information architecture, user journey and flow, naming, UI, states and messaging, handoff, design QA." },
          { label: "COLLABORATION", text: "scope and priorities. Engineering team — technical constraints, from day one. Customer Success — insight into what people didn't understand on calls. Plus support from QA and the writer." },
        ],
      },
    },
    problem: {
      eyebrow: "02 · Knowledge gathering",
      title: "The knowledge already lived in the team",
      introPre: "Client Acquisition reached people ",
      introBold: "whose behavior I'd already studied",
      introRest: " on other projects at Localo. So I went in with a ready persona and knowledge of how they work day to day and what they need.",
      persona: {
        overline: "WHO IT'S FOR (PERSONA)",
        quote: "Freelancers, SEO specialists, and people at agencies responsible for client acquisition.",
        commonBold: "What they have in common: ",
        commonText: "they don't come for data — they come for an answer to who should I call tomorrow and what do I show them.",
      },
      sourcesTitle: "Sources of knowledge and key findings",
      sourcesIntro: "The project scope didn't call for fresh discovery or deeper research. I relied on four sources that spoke directly to this feature: my own ",
      sourcesIntroBold: "expert audit, session recordings, support tickets, and Customer Success's knowledge.",
      auditTitle: "Expert audit",
      auditItems: ["Experience", "Nielsen's 10 heuristics", "Guidelines & best practices", "Accessibility"],
      moreSourcesLead: "On top of that, I looked for information in these places:",
      sourceCards: [
        { title: "Session recordings in Clarity", text: "The audit tells you what's broken by the rules. Recordings tell you where people actually stop, what they click, and at what point they close the tab." },
        { title: "Conversations with Customer Success", text: "They'd explained this feature live dozens of times, so they knew things about it that don't show in the interface: exactly what they tell clients, what users struggle with most, and the moment the lightbulb goes on." },
        { title: "Support tickets", text: "I went through the tickets about the feature: a list of frustrations, problems, and requests for help. Questions about credits kept coming back — and that report later became a concrete change in the project." },
        { title: "Session with engineers", text: "I pulled in the engineering team before I sketched anything. I wanted to know how the feature works today and why, what our technical constraints are, what's blocking us, and what we already know we want to drop or move to a different stack." },
      ],
      aiSynthesisTitle: "AI-assisted research synthesis",
      aiSynthesisText: "I combined the Clarity recordings, support conversations, and expert-audit findings using Claude. I wanted to see where the observations overlapped, whether patterns emerged, and which recorded frustrations came up most often.",
      findingsTitle: "Key findings",
      findings: [
        { number: "01", title: "High barrier to entry", text: "Every new user needed manual onboarding from CS. Walking into the tool, they had no idea what they'd get." },
        { number: "02", title: "Results weren't repeatable", text: "The same query could return a different list, with no way back to the previous one — no snapshots, no search history." },
        { number: "03", title: "No continuity", text: "Leads lived in Sales mode, visibility data in Research, with no shared context and no visible link between them." },
        { number: "04", title: "External tools", text: "One task, several exits from the tool. A lead was a row with no data to decide on — no site, review count, or map link, those were still project goals — while contact status and notes lived in someone else's spreadsheet." },
        { number: "05", title: "Invisible cost", text: "No communication of limits. Nowhere did it say how many credits a user had, what an action cost, or what happens when they run out." },
      ],
      scopeTitle: "Scope — what we're doing and what we're not",
      scopeIntro: "Together with the PM and the team, I nailed down exactly what was in scope for the redesign. That included: ",
      scopeIntroBold: "stabilizing list generation, a micro-CRM with lead statuses, a better lead preview, communicating limits, communicating value, naming, and a visible link between both halves of the feature.",
      scopeIntroEnd: " We deliberately excluded three things:",
      scopeOut: [
        { title: "How keywords are added.", text: "We used it in other parts of the app, so changing it here would mean rethinking it everywhere. ", textBold: "That needed a project of its own." },
        { title: "Result history.", text: "It only becomes worth something once people come back to the feature. ", textBold: "First we had to check whether they would." },
        { title: "Buying extra credits.", text: "Bundles, price tiers, one-off billing or added to the subscription — that's a pricing-model decision and ", textBold: "needs a conversation with the business." },
      ],
      scopeClosing1Pre: "That list did two things: ",
      scopeClosing1Bold: "it kept us disciplined",
      scopeClosing1Rest: " — whenever we drifted off with ideas, we came back to the \"agreement,\" which kept us from burying ourselves in one project for six months. It also aligned expectations: the manager knew what the output would be, and the engineers and I knew what we were responsible for.",
      scopeClosing2: "As always, and this time too, I put together a goal that was presented to and approved by the team. That way, at every stage of the project, we remember who it's for and why we're doing it.",
      goalOverline: "GOAL",
      goalPre: "Take the burden of explaining the feature off the team. ",
      goalBold: "Users should walk in, see the result, and keep using it on their own",
      goalRest: " — no call, no instructions, no leaving for outside tools.",
    },
    discovery: {
      eyebrow: "03 · Process",
      title: "The path first, then the screens",
      flow: {
        title: "New flow, before the first screen existed",
        text1: "I remapped the entire user journey from scratch: from finding a business, through lead scoring and a visibility scan, to the material to send, contact status, and profile activation. This wasn't redrawing what already existed — neither of the two modes carried the whole journey, so it had to be assembled.",
        text2: "The map gave the team a shared picture of the scope, surfaced edge cases before they became a design problem, and set the structure the entire feature was later built on.",
      },
      lowfiTitle: "Low-fi, before anything looked like anything",
      lowfiIntro: "Before the polished mockups, I made a draft and a low-fi prototype. I wanted to check the layout, but mainly to make sure we understood how the feature works today and how we wanted it to work. With a feature someone else had built earlier, that's not obvious — not to me, and not to the team.",
      decisionsTitle: "Key decisions",
      decision1: {
        title: "One place to work from",
        rejectedLabel: "Rejected option:",
        rejectedPre: "keep Sales mode and Research mode ",
        rejectedBold: "separate",
        rejectedRest: ", linked by navigation and onboarding. Logically clean — one is analysis, the other is sales.",
        reasonLabel: "Reason:",
        reasonText: "the work is sequential — first find the business, then prepare material for it. Going from \"oh, a potential client\" to \"generate them a position map\" needed to be one motion, and the line between modes ran right through it.",
      },
      namingCard: {
        title: "Names tell you what happens",
        text: "Sales mode and Research mode → Client Acquisition with two modules: Leads finder and Visibility scans. The old names described the tool's working mode; the new ones describe what the user gets. It looks cosmetic, and it was one of the cheapest changes that raised how understandable the feature was. The name is the first tooltip a user sees — and the only one they can't skip.",
      },
      resultCard: {
        title: "One score instead of five numbers",
        para1: "Leads get a Growth Potential score — one value that speeds up filtering potential clients.",
        reasonLabel: "Reason:",
        para2: " raw metrics pushed the \"is this worth it\" calculation onto the user, and that ",
        reasonBold: "needs knowledge and time to analyze.",
        para3: " The raw data stayed, but from now on it's only used for deeper analysis — Localo does the first pass.",
      },
    },
    handoff: {
      eyebrow: "05 · Handoff & development",
      title: "Handoff — what the developers got",
      introPre: "Developers got Figma mockups ",
      introBold: "laid out as a flow",
      introRest: ": every state, notification examples, mobile versions, and implementation notes wherever a decision was needed. On top of that, edge-case descriptions — what happens when there's no data — design-system tokens, and a clickable prototype, so the whole thing could be walked through before writing a single line of code.",
      intro2Pre: "I stayed ",
      intro2Bold: "in constant contact with the developers",
      intro2Rest: ", so questions got resolved on the spot. I checked the implementation on the staging environment and flagged differences from the design. I supported QA in defining what needed testing, and collected fixes after launch.",
      blurCaption: "Blurred for data security reasons",
    },
    rozwiazanie: {
      eyebrow: "04 · Final solution",
      title: "From lead to client",
      intro: "Below is the final solution. The user enters an industry and city, gets a list of businesses, and picks the one where showing results will be easiest. They check its visibility, send a position map under their own brand, and note what they agreed on the phone. When the client says yes, they activate their profile. All in one tool, from the first search to the first day of the partnership.",
      leadsFinderTitle: "Leads Finder — finding potential clients",
      b1: {
        title: "A separate list for every search",
        text: "Every project is a leads list built around one keyword and one location — dentists in Torun and hairdressers in Warsaw can run side by side. The status on the card shows what's in progress, what's closed, and what's still left over from the previous version of the feature.",
      },
      b2: [
        { title: "A Legacy tag on migrated lists", text: "Old data couldn't be pulled into the new structure. Migrated lists get a Legacy tag, so it's clear the result might differ slightly from newer ones." },
        { title: "Cost visible before you click", text: "Credit balance and the price of the action sit in the same window where the user types the keyword and location. The limit stopped being a surprise you had to ask support about." },
      ],
      b3: {
        title: "Users shape the list their own way",
        text: "Filters and sorting narrow the list down to the businesses that matter and put them in the order they should be called.",
      },
      b4: [
        { title: "Growth Potential points to the best leads", text: "One value shows how easy it'll be to demonstrate results for a given business. The higher it is, the faster the payoff — the user sorts the list and gets the best leads at the top." },
        { title: "Proof for the call in one click", text: "Green dots mean visibility, red means none, orange means a weak position. The position map is generated from the leads list and sent as a link with no Localo logo, under the agency's own brand." },
      ],
      b5: [
        { title: "A place for your own notes", text: "For every lead, the user jots down what will help in the next conversation. No need for separate per-client notes." },
        { title: "Contact status on every lead", text: "The user marks what stage the conversation with a given business is at, in the same view where they found that business. A spreadsheet kept alongside Localo stopped being necessary." },
      ],
      b6: {
        title: "Sales material without using up a slot",
        text: "While the conversation is ongoing, the user generates more position maps for more keywords. They pay with credits from their plan, but don't add someone else's profile to Localo and don't use up a slot — the profile stays in Client Acquisition until there's a deal.",
      },
      b7: {
        title: "Activating a new profile",
        text: "Once the client agrees, the user activates their profile in Localo and starts monitoring and optimization. Only this step uses up a slot in the plan.",
      },
    },
    wynik: {
      eyebrow: "06 · Results",
      title: "What the numbers showed",
      heroStat: { value: "+81%", label: "longer median session on the feature: from 4.0 to 7.3 minutes. In prospecting, longer means better. Someone who sits in the lead list for seven minutes has started using it." },
      sessionsStat: { value: "3,425 → 8,403", label: "Sessions on the feature" },
      smallStats: [
        { value: "5.5×", label: "Feature users pay more often" },
        { value: "9x", label: "Higher blended LTV per feature user" },
      ],
      dataCaption: "Period: August-November 2025 for the old version, December 2025-June 2026 for the new one; the switch happened in December 2025.",
      whatItMeansTitle: "What's behind these numbers",
      para1Pre: "The goal from the brief closed beyond the data too. As the CS team reports - ",
      para1Bold: "the number of onboarding calls dropped",
      para1Rest: ", the feature stopped being something they had to explain live.",
      para2Bold: "The feature grew faster than the app itself",
      para2Rest: ". The user base went from 4.1k to 6.7k MAU in that time, and the feature's share of active users still rose from ~7.3% to ~7.8%. Holding that share while the base grew by two-thirds means the feature was picking up new people faster than the product was.",
      para3Pre: "People started sticking around in the feature. Median session length grew 81%, session count grew 145%, and events per session barely moved: 11.2 → 12.1. They're not clicking more — yet they're ",
      para3Bold: "spending more time there",
      para3Rest: ". When you're working a lead list and a position map, that's exactly the point.",
      para4: "The feature landed in the most valuable segment. Client Acquisition users pay 5.5× more often than the rest of the base and have roughly 9x higher blended LTV. It's a tool for freelancers and agencies — the people who spend the most in Localo — and it answered a real need for them.",
    },
    podsumowanie: {
      eyebrow: "07 · Takeaways",
      title: "Execution, not discovery",
      intro: "This wasn't a classic project: discovery, research, design, delivery. It's an example of a well-executed assigned task. From the meetings, we knew that once users were introduced to the feature, they saw the value and used it willingly. My job was to make the interface do that, not the team.",
      lessons: [
        { title: "Developers' voice in the project matters", text: "I brought engineers in before the first mockup, and that was the best process decision in this project. Legacy data still surfaced along the way and had to be solved with design — a Legacy tag on the card. Talking earlier doesn't guarantee nothing will come up. It guarantees it comes up with you, not in production." },
        { title: "What I'd do differently", text: "We moved testing to production, and there's one thing I'd do differently: Growth Potential. It's the only place where the user hands the decision to an algorithm, and the algorithm went out to people without checking whether its result matched their intuition." },
      ],
    },
  },
}
