export const copy = {
  pl: {
    heroEyebrow: "CASE STUDY - LOCALO · CLIENT ACQUISITION",
    heroTitle: "do pozyskiwania klientów.",
    heroTitleAccent: "Jeden flow",
    heroLead:
      "Generowanie leadów i research widoczności istniały w Localo osobno. Obydwa działały i praktycznie nikt nie uruchamiał ich sam – wartość docierała do ludzi dopiero na callu z Customer Success. Do tego jedno i drugie kończyło się w zewnętrznym CRM-ie albo w arkuszu. Zaprojektowałam Client Acquisition: jedno narzędzie z dwoma modułami, które tłumaczy się samo i domyka zadanie bez wychodzenia na zewnątrz. Po redesignie mediana sesji na funkcji wzrosła z 4,0 do 7,3 minuty, a liczba calli onboardingowych spadła.",
    metaBar: [
      { label: "PRODUKT", value: "Localo" },
      { label: "SKALA", value: "6 700+ użytkowników" },
      { label: "BRANŻA", value: "Local SEO / B2B SaaS" },
      { label: "UŻYTKOWNICY", value: "Freelancerzy, specjaliści SEO, agencje" },
    ],
    chapters: {
      skrot: "01 W skrócie",
      problem: "02 Wiedza",
      discovery: "03 Discovery",
      reframing: "04 Re-framing",
      decyzje: "05 Decyzje",
      handoff: "06 Handoff",
      rozwiazanie: "07 Rozwiązanie",
      wynik: "08 Wynik",
      podsumowanie: "09 Podsumowanie",
    },
    skrot: {
      eyebrow: "01 · KONTEKST, EFEKT I ROLA",
      title: "W skrócie",
      introBold: "Localo to narzędzie dla osób, które zarządzają wizytówkami Google",
      introRest:
        " — jedną albo kilkudziesięcioma naraz. Automatyzuje pracę i mówi, co zrobić dalej: lista zadań na tydzień z priorytetami dla każdej wizytówki, audyty w kilka sekund, raporty gotowe do wysłania klientowi w kilka minut.",
      contextPanel: {
        title: "Brief — Client Acquisition",
        text1: "Funkcja powstała w ramach MVP, zbudował ją dev i została taka, jaka była. Nikt w zespole nie udawał, że jest dobrze.",
        text2: "„Wiemy, że UX i generalnie projekt tej funkcji jest słaby – użytkownicy dopiero po onboardingu przez Customer Success, na callach, są w stanie zrozumieć wartość narzędzia i jakkolwiek z niego korzystać. Chcemy, żeby użytkownicy weszli, zobaczyli efekt wow i sami z tego korzystali.”",
      },
      closingLead: "To nie był projekt, w którym trzeba było odkryć problem. Problem był znany - ",
      closingBold: "Cała robota była w tym, jak to zrobić.",
      statsIntroTitle: "Jak zmieniły się metryki:",
      stats: [
        { value: "+81%", label: "dłuższa mediana sesji na funkcji: 4,0 → 7,3 min" },
        { value: "5,5x", label: "częściej płacą użytkownicy funkcji niż reszta bazy: 28,0% vs 5,1%" },
        { value: "~9x", label: "wyższe blended LTV użytkownika funkcji: $149,97 vs $16,31" },
      ],
      statsCaption: "Dwie ostatnie to porównanie użytkowników funkcji z resztą bazy, nie pomiar przed i po. Rozbieram to w rozdziale 07.",
      roleOverline: "MOJA ROLA — DESIGN LEAD OD A DO Z",
      roleQuote: "W Localo odpowiadałam za cały produkt – od discovery po delivery.",
      roleList: [
        "definiowałam problemy",
        "prowadziłam badania i projektowałam UI/UX",
        "testowałam z użytkownikami i iterowałam",
        "doradzałam, co wchodzi na roadmapę, a co nie",
        "rozwijałam design system i utrzymywałam go wspólnie z devami",
        "chodziłam na rozmowy z klientami, żeby nie opierać się na cudzych notatkach",
        "mentorowałam młodszą projektantkę",
      ],
      scopePanel: {
        title: "Redesign: Research & Sales mode",
        blocks: [
          { label: "MÓJ ZAKRES", text: "audyt ekspercki istniejącej funkcji, nowa architektura informacji, user journey i flow użytkownika, nazewnictwo, UI, stany i komunikaty, handoff, design QA." },
          { label: "WSPÓŁPRACA", text: "zakres i priorytety. Zespół developerski – ograniczenia techniczne, od początku. Customer Success – wiedza o tym, czego ludzie nie rozumieli na callach. Do tego wsparcie QA i writera." },
        ],
      },
    },
    problem: {
      eyebrow: "02 · Zbieranie wiedzy",
      title: "Wiedza była w zespole",
      introPre: "Client Acquisition trafiał do ludzi, ",
      introBold: "których zachowania zgłębiałam już wcześniej",
      introRest: ", przy innych projektach w Localo. Siadałam więc do tego z gotową personą i z wiedzą o tym, jak pracują na co dzień i jakie potrzeby mają.",
      persona: {
        overline: "KOGO DOTYCZY (PERSONA)",
        quote: "Freelancerzy, specjaliści SEO i osoby odpowiedzialne w agencji za pozyskiwanie klientów.",
        commonBold: "Wspólne dla nich: ",
        commonText: "nie przychodzą po dane, tylko po odpowiedź na pytanie do kogo mam jutro zadzwonić i co mu pokażę.",
      },
      sourcesTitle: "Źródła wiedzy i kluczowe odkrycia",
      sourcesIntro: "Zakres projektu nie przewidywał ponownego discovery ani głębszych badań. Oparłam się na czterech źródłach, które mówiły wprost o tej funkcji: własnym ",
      sourcesIntroBold: "audycie eksperckim, nagraniach sesji, zgłoszeniach do supportu i wiedzy Customer Success.",
      auditTitle: "Audyt ekspercki",
      auditItems: ["Doświadczenie", "10 Heurystyk Nielsena", "Wytyczne i najlepsze praktyki", "Dostępność"],
      moreSourcesLead: "Ponad to szukałam jeszcze informacji w tych miejscach:",
      sourceCards: [
        { title: "Nagrania sesji w Clarity", text: "Audyt mówi, co jest zepsute według zasad. Nagrania mówią, gdzie ludzie faktycznie się zatrzymują, co klikają i w którym momencie zamykają kartę." },
        { title: "Rozmowy z Customer Success", text: "Oni tłumaczyli tę funkcję na żywo dziesiątki razy, więc wiedzieli o niej rzeczy, których nie widać w interfejsie: co dokładnie opowiadają klientom, z czym użytkownicy mają największy problem i w którym momencie zapala im się światełko, że to ma sens." },
        { title: "Tickety supportu", text: "Przejrzałam zgłoszenia dotyczące funkcji: to jest lista frustracji, problemów czy potrzeba pomocy. Głównie wracały w nich pytania o kredyty – i to zgłoszenie wróciło potem jako konkretna zmiana w projekcie." },
        { title: "Sesja z developerami", text: "Wciągnęłam zespół developerski, zanim cokolwiek narysowałam. Chciałam wiedzieć, jak ta funkcja działa dziś i dlaczego tak, jakie mamy ograniczenia techniczne, co nas blokuje i z czego już wiadomo, że chcemy zrezygnować albo przenieść na inną technologię." },
      ],
      aiSynthesisTitle: "Synteza badań z AI",
      aiSynthesisText: "Połączyłam nagrania z Clarity, rozmowy z supportem i spostrzeżenia z audytu eksperckiego za pomocą Clauda. Chciałam zobaczyć gdzie spostrzeżenia się pokrywają, czy powstają wzorce oraz które odnotowane frustracje pojawiają się najczęściej.",
      findingsTitle: "Kluczowe odkrycia",
      findings: [
        { number: "01", title: "Wysoka bariera wejścia", text: "Każdy nowy użytkownik wymagał ręcznego onboardingu od CS. Użytkownik wchodząc do narzędzia, nie wiedział co dostanie." },
        { number: "02", title: "Wyniki nie były powtarzalne", text: "To samo zapytanie potrafiło zwrócić inną listę, a nie było jak wrócić do poprzedniej – bez snapshotów i bez historii wyszukiwań." },
        { number: "03", title: "Brak ciągłości", text: "Leady w Sales mode, dane o widoczności w Research, bez wspólnego kontekstu i bez widocznego połączenia między nim." },
        { number: "04", title: "Zewnętrzne narzędzia", text: "Jedno zadanie, kilka wyjść z narzędzia. Lead był wierszem bez danych do decyzji – brak strony, liczba opinii i link do map to były dopiero cele projektu – a statusy kontaktu i notatki mieszkały w cudzym arkuszu." },
        { number: "05", title: "Niewidoczny koszt", text: "Brak komunikacji limitów. Nigdzie nie było wiadomo, ile użytkownik ma kredytów, ile kosztuje akcja ani co się stanie, gdy się skończą." },
      ],
      scopeTitle: "Zakres, czyli co robimy, a czego nie",
      scopeIntro: "Z PM-em i zespołem ustaliłam dokładnie, co wchodzi w zakres redesignu. Weszły m.in.: ",
      scopeIntroBold: "stabilizacja generowania list, mikro-CRM ze statusami leadów, lepszy podgląd leada, komunikacja limitów, komunikacja wartości, nazewnictwo oraz widoczne połączenie między obiema częściami funkcji.",
      scopeIntroEnd: " Trzy rzeczy wykluczyliśmy świadomie:",
      scopeOut: [
        { title: "Sposób dodawania keywordów.", text: "Korzystaliśmy z niego w innych miejscach aplikacji, więc zmiana tutaj oznaczałaby przemyślenie go wszędzie. ", textBold: "Na to potrzeba było osobnego projektu." },
        { title: "Historia wyników.", text: "Zaczyna być coś warta dopiero wtedy, gdy ludzie wracają do funkcji. ", textBold: "Najpierw trzeba było sprawdzić, czy wrócą." },
        { title: "Dokupowanie kredytów.", text: "Paczki, przedziały cenowe, rozliczenie jednorazowe czy doliczane do abonamentu — to decyzja o modelu płatności i ", textBold: "wymaga rozmowy z biznesem." },
      ],
      scopeClosing1Pre: "Taka lista zrobiła dwie rzeczy: ",
      scopeClosing1Bold: "trzymała nas w ryzach",
      scopeClosing1Rest: " – kiedy odpływaliśmy z pomysłami, wracaliśmy do „umowy”, dzięki czemu nie zakopaliśmy się w jednym projekcie na pół roku. Wyrównała też oczekiwania: manager wiedział, jaki będzie output, a ja i devowie wiedzieliśmy, za co odpowiadamy.",
      scopeClosing2: "Zawsze też, i tym razem również, sformułowałam cel, który został przedstawiony i zatwierdzony przez zespół. Dzięki temu na każdym etapie projektu pamiętamy, dla kogo i po co to robimy.",
      goalOverline: "CEL",
      goalPre: "Zdjąć z zespołu obowiązek tłumaczenia funkcji. ",
      goalBold: "Użytkownik ma wejść, zobaczyć wynik i korzystać dalej sam",
      goalRest: " – bez calla, bez instrukcji, bez wychodzenia do zewnętrznych narzędzi.",
    },
    discovery: {
      eyebrow: "03 · DISCOVERY",
      title: "Czego nie wiedzieliśmy o klientach naszych klientów.",
      intro1Bold: "osiem wywiadów pogłębionych",
      intro1Pre: "Miałam na discovery dwa tygodnie i robiłam je sama. Przy takich warunkach zdecydowałam się na ",
      intro1Rest:
        " — mix agencji i freelancerów — żeby zrozumieć kształt problemu: jak raportują dzisiaj i o co pytają ich klienci, jakich narzędzi, słów, kolorów i form używają, co klient robi z raportem po otrzymaniu. Najbardziej interesował mnie język, w jakim tłumaczą wyniki komuś, kto nie zna się na SEO. I to, kim są twórcy raportów, a kim ich odbiorcy.",
      intro2Pre: "Równolegle przygotowałam ",
      intro2Bold: "ankietę ilościową (około 100 odpowiedzi)",
      intro2Rest:
        " żeby wiedzieć, co i jak często użytkownicy raportują. Wywiad mówi, dlaczego ktoś coś robi. Ankieta mówi, ile osób robi to samo. Od tego zależało, co znajdzie się w raporcie, a domyślny raport miał być tym, którego nikt nie musi poprawiać.",
      stats: [
        { value: "8", label: "Wywiadów pogłębionych" },
        { value: "100+", label: "Odpowiedzi\nz ankiet" },
      ],
      intro3Bold: "Trzecim źródłem był zespół customer success",
      intro3Rest:
        ". Są blisko użytkowników i ich problemów na co dzień, więc poza spotkaniem przejrzeliśmy razem zgłoszenia. Stąd wiem, ile z nich dotyczyło pytań o API do Localo — wrócę do tego przy kluczowych decyzjach — i jakim językiem nasi użytkownicy mówią o swoich klientach.",
      intro4: "Połączyłam dane jakościowe i ilościowe w jeden spójny obraz używając do tego AI w postaci Clauda aby przyspieszyć ten etap pracy. Przeanalizował dla mnie materiały z badań ilościowych, jakościowych oraz transkrypty ze spotkań.",
      findingsTitle: "Kluczowe odkrycia",
      findings: [
        { number: "01", title: "Raport jest skanowany, nie analizowany", text: "Klient końcowy prowadzi własną firmę i nie siada do analizy liczb. Przelatuje raport wzrokiem." },
        { number: "02", title: "Składanie raportu to godziny, co miesiąc, od nowa", text: "Zbierali dane z kilku narzędzi i składali je ręcznie w jedną prezentację. Mówili wprost, że chętnie by to zautomatyzowali." },
        { number: "03", title: "Potrzeba edukacji klienta", text: "Do raportów często dołączano osobne wyjaśnienia: czym są dane i dlaczego mają znaczenie dla klienta." },
      ],
      personaTitle: "Klienci naszych klientów — persona",
      personaIntroBold: "Raporty mają dwóch odbiorców.",
      personaIntroRest: " Specjalista tworzy raport i pokazuje nim klientowi, że praca przynosi efekty. Klient końcowy tylko go skanuje. Projektowałam więc także dla kogoś, kto nie jest użytkownikiem naszego produktu.",
      personaCards: [
        { title: "Kim jest", text: "Nietechniczny właściciel firmy. Nie zna się na SEO i nie ma konta w Localo." },
        { title: "Czego chce", text: "Dwóch odpowiedzi: „czy jest lepiej” i „co mi to daje”." },
        { title: "Jak czyta", text: "Przelatuje raport wzrokiem. Nie ma czasu, umiejętności ani chęci, żeby analizować liczby i wykresy." },
      ],
    },
    reframing: {
      eyebrow: "04 · RE-FRAMING",
      title: "Problemem nie był dostęp, tylko wysiłek",
      text: "Hipoteza, z którą zaczynaliśmy, nie obroniła się w badaniach. Problemem nie był dostęp do danych — tylko wysiłek i zaangażowanie, których wejście do narzędzia wymagałoby od klienta. To odwróciło kierunek: zamiast wpuszczać klienta do Localo, trzeba było wypchnąć raport do niego.\n\nPrzedstawiłam CEO wyniki badań, sformułowany problem i nową hipotezę. Przyjął je bez oporu — dane były jednoznaczne. Cel projektu ustaliliśmy wspólnie.",
      shiftTitle: "Zmiana kierunku",
      hypothesisRejected: {
        title: "Hipoteza na starcie",
        status: "Obalona",
        text: "Wpuśćmy klienta do narzędzia w trybie tylko do odczytu, a sam sprawdzi swoje dane. Problemem nie był dostęp, tylko wysiłek i zaangażowanie.",
      },
      hypothesisLive: {
        title: "Hipoteza właściwa",
        status: "New!",
        note: "Sprawdzian: jaki udział użytkowników raportów włącza automat i jaka część z nich nie generuje ręcznie w ogóle.",
        text: "Jeśli raport będzie powstawał sam i trafiał do klienta, specjaliści przejdą na autoraportowanie i przestaną tworzyć raporty ręcznie.",
      },
      goalLabel: "Zbudować narzędzie do ",
      goalBold1: "automatycznego raportowania",
      goalMid: ", które jasno pokazuje wyniki nietechnicznym klientom i ",
      goalBold2: "buduje zaufanie do współpracy",
      goalEnd: ".",
    },
    decyzje: {
      eyebrow: "05 · KLUCZOWE DECYZJE I KOMPROMISY",
      title: "Decyzje, które wpłynęły na kierunek",
      mainDecision: {
        title: "Generowanie z pełnych danych, selekcja dopiero przed wysyłką raportu",
        steps: [
          { label: "Odrzucony wariant:", text: "Wybór elementów raportu przed generowaniem wydawał się logicznym flow. Utwórz raport → z okresu → wybierz dane → generuj." },
          { label: "Powód:", bullets: [
            { text: "każdy nowy raport generuje mapę pozycji, ", bold: "a to kosztuje" },
            { text: "przy wyborze przed generowaniem użytkownik produkowałby nowy raport przy każdej zmianie zdania", bold: "" },
          ] },
          { label: "Efekt:", text: "Niższy koszt po naszej stronie i mniejsze tarcie po stronie użytkownika. Jedna decyzja, dwa wygrane fronty." },
        ],
      },
      pair: [
        {
          title: "Kreator jako\nasystent, nie pusty formularz",
          image: "/raporty-ds-smart-creator.webp",
          text1: "Raport generuje się sam, a użytkownik dostaje gotowy draft. Zmienia/Akceptuje i wysyła. Ostatnie słowo zostaje po jego stronie: automat przygotowuje, ale ",
          text1Bold: "nie decyduje za niego.",
          text2Bold: "Powód:",
          text2: "Projektowanie w zgodzie z misją firmy: automatyzacja wykonania, nie zastąpienie rozumienia.",
        },
        {
          title: "Nie zbudowaliśmy API",
          image: "/raporty-ds-api-stop.webp",
          text1: "Użytkownicy wprost prosili o API do samodzielnego tworzenia raportów we własnym frameworku. Nie poszliśmy tą drogą: funkcja odpowiadała na potrzebę wąskiej grupy, a wymagała dużo pracy po stronie developmentu.",
          text1Bold: "",
          text2Bold: "Efekt:",
          text2: "Na obecnym etapie nakład pracy był nieproporcjonalny do zysku. Zapisaliśmy ten pomysł do backlogu.",
        },
      ],
      builtTitle: "Co zbudowałam",
      builtText: "Raportowanie i autoraportowanie. Użytkownik ustawia — globalnie albo osobno dla konkretnej wizytówki — jak często ma się generować raport. Wybiera na przykład raz w miesiącu i co miesiąc dostaje gotowy dokument z najważniejszymi informacjami o wizytówce: pozycjami słów kluczowych i ich zmianami, aktywnością na profilu, opiniami. Może włączać i wyłączać poszczególne sekcje, żeby nie zaśmiecać raportu tym, co dla jego klienta nie ma znaczenia. Dodaje adres i wysyła.",
      testsTitle: "Testy użyteczności",
      testsText: "Zmapowałam pełny flow tworzenia raportu, zbudowałam klikalny prototyp w Claude Code aby przetestować go z użytkownikami, zanim zaangażowałam development i QA. Przygotowałam scenariusze aby odpowiedzieć na 3 pytania:",
      testsQuestions: [
        "Czy kroki w procesie tworzenia raportu są przewidywalne?",
        "Czy użytkownik bez problemu odnajduje raport konkretnej wizytówki w managerze raportów i czy rozumie status?",
        "Czy kreator (edycja draftu i wysyłka) jest łatwy w obsłudze?",
      ],
      testsFindings: [
        { title: "Lista była zorganizowana odwrotnie niż praca użytkownika.", text1: "Manager pokazywał wszystkie raporty wygenerowane dla wszystkich wizytówek. Użytkownicy gubili się na tej liście i mieli problem z nawigacją.", text2: "Powód okazał się fundamentalny: ich codzienna praca jest zorganizowana per wizytówka, więc myślą w kolejności profil → raport. Moja lista pokazywała odwrotnie: raport → dla profilu XYZ. To nie był problem etykiet, tylko niedopasowania do modelu mentalnego." },
        { title: "Historia raportów była nieprzydatna.", text1: "Jedyna informacja, której respondenci naprawdę szukali, brzmiała: czy najnowszy raport jest jeszcze szkicem, czy poszedł już do klienta.", text2: "" },
      ],
      testsClosing: "W kolejnej turze wszyscy respondenci poruszali się po funkcji bez zająknięcia. Sprawnie radzili sobie z zadaniami np. znajdź najnowszy raport dla wizytówki xyz lub wygeneruj raport dla 4 wizytówek na raz. Wersje po zmianach pokażę w kolejnych krokach.",
    },
    handoff: {
      eyebrow: "06 · HANDOFF I DEVELOPMENT",
      title: "Handoff to coś więcej niż przekazanie makiet",
      introBold: "w Figmie ułożone we flow",
      introPre: "Devowie dostali makiety ",
      introMid: ", a nie luźne ekrany: wszystkie stany, przykłady notyfikacji, wersje mobilne i adnotacje wdrożeniowe w miejscach, które wymagały decyzji. ",
      introBold2: "Do tego opis sytuacji brzegowych",
      introRest: " — co się dzieje, kiedy danych nie ma — tokeny z design systemu i klikalny prototyp, żeby dało się przejść całość przed napisaniem pierwszej linijki kodu.",
      intro2Pre: "Byłam z devami ",
      intro2Bold: "w kontakcie na bieżąco",
      intro2Rest: ", więc pytania rozstrzygały się od ręki, zamiast czekać na review. Sprawdzałam wdrożenie na środowisku testowym i zgłaszałam różnice względem projektu. Wspierałam QA przy definiowaniu tego, co trzeba sprawdzić, a po wdrożeniu zbierałam poprawki.",
      infraTitle: "Jedna z funkcji przegrała z infrastrukturą",
      infraText1: "W raportach wysyłanych mailem miały być interaktywne mapy pozycji. Kliknięcie w mapę otwierałoby link, w którym klient mógłby sam pozmieniać ustawienia i podejrzeć dane. Funkcja była gotowa i nie weszła. Zobaczyliśmy to przed releasem: klienty pocztowe radzą sobie z linkami słabo — filtry je wykrywały i testowe wiadomości trafiały do spamu. Nie mieliśmy dość czasu, żeby to obejść, więc wycięliśmy interaktywne mapy z raportów wysyłanych mailem.",
      infraText2: "To najbardziej frustrujący moment tego projektu. Funkcja działała i była dobra — przegrała z infrastrukturą. Dobra wiadomość jest taka, że dowiedzieliśmy się o tym my, a nie użytkownicy.",
    },
    rozwiazanie: {
      eyebrow: "07 · ROZWIĄZANIE",
      title: "Jak to wyszło — raport od ręki",
      intro: "Poniżej finalna wersja modułu raportów i managera raportów – ta, która weszła na produkcję i z której użytkownicy korzystają na co dzień. Od listy raportów pojedynczej wizytówki, przez sam raport, po zarządzanie całym portfolio klientów.",
      s1Title: "Lista raportów – historia jednej wizytówki",
      s1CardTitle: "Draft już czeka",
      s1CardText: "Użytkownik nie zaczyna od pustego kreatora. Otwiera wizytówkę, a draft za bieżący okres już tam jest – zostaje przejrzeć i wysłać. Każdy raport na liście ma okres, datę wygenerowania i status. Stąd też ustawia się auto-raportowanie.",
      s2Title: "Raport",
      s2Text: "Raport startuje kompletny – statystyki, frazy z mapami pozycji, opinie, treści, cytowania i konkurencja. Wszystko z okresu, nic nie trzeba dobierać. Logo agencji na górze, a przy metrykach krótkie wyjaśnienie, co znaczą.",
      s2Pair: [
        { title: "Dopasowuję do konkretnego klienta", text: "Odznacza to, nad czym w tym miesiącu nie pracował. Raport ma odpowiadać na „czy jest lepiej”, a nie pokazywać wszystko, co system umie policzyć." },
        { title: "Auto-raportowanie", text: "Auto-raporty włączone są domyślnie. Można edytować zakres danych – np. miesiąc – i częstotliwość generowania w dowolnym momencie." },
      ],
      s3Title: "Manager — lista wizytówek, nie lista raportów",
      s3CardTitle: "Widok z lotu ptaka",
      s3CardText: "Kto ma pod sobą kilkanaście wizytówek, potrzebuje widoku na całe portfolio klientów. To układ po testach użyteczności: najpierw klient, potem jego raport.",
      s3Pair: [
        { title: "Statusy i harmonogram", text: "Widzi, co poszło do klienta i kiedy wygeneruje się następny raport. Bez wchodzenia w każdą wizytówkę osobno." },
        { title: "Wiele raportów na raz", text: "Jeśli potrzebuje raportu poza stałym harmonogramem, zrobi to akcją zbiorczą." },
      ],
      s3Triple: [
        { title: "Wysyłka", text: "Trzema sposobami z jednego ekranu: auto-wysyłka, link bez logowania lub PDF." },
        { title: "Wysyłka mailem", text: "Raport idzie do klienta – klient nie idzie do raportu." },
        { title: "Wysyłam mailem", text: "Raport idzie do klienta – klient nie idzie do raportu." },
      ],
      s4Title: "Komponenty i stany",
      s4Text: "Każdy komponent musiał obsłużyć wszystkie stany – pusty, w trakcie generowania, wysłany, błąd. Notyfikacje, empty state'y, dropdowny i tagi wzięłam z design systemu, który rozwijałam razem z devami.",
    },
    wynik: {
      eyebrow: "08 · WYNIK I DOWODY",
      title: "Co pokazały liczby",
      heroStat: { value: "11–13%", label: "aktywnych użytkowników tworzy raport w danym miesiącu — mniej więcej jeden na dziewięciu zmienił nawyk" },
      smallStats: [
        { value: "60%", label: "użytkowników włączyło auto generowanie" },
        { value: "~11×", label: "częściej płacą niż reszta bazy" },
        { value: "44%", label: "nie tworzy już raportu ręcznie" },
        { value: "~20x", label: "wyższe blended LTV niż reszta bazy" },
      ],
      dataCaption: "Dane z okresu październik 2025 – czerwiec 2026, od analityka danych w Localo.",
      whatItMeansTitle: "Co za tymi liczbami stoi",
      para1: "Przez dziewięć miesięcy udział twórców raportów trzyma się w przedziale 11–13%. Po premierze urósł, w grudniu sięgnął szczytu, potem osiadł nieco niżej — ale się utrzymał. ",
      para1Bold: "To nie jest krzywa świeżej funkcji, tylko nowy nawyk.",
      para2: "44% z kolei to nie jest adopcja, ",
      para2Bold: "to zmiana nawyku",
      para2Rest: ". Ci ludzie przestali robić ręcznie coś, co robili ręcznie od zawsze. Auto jest tu trybem dominującym, nie dodatkiem — i to jest dla mnie najmocniejsza liczba na tej liście.",
      para3: "Użytkownicy raportów płacą ~11× częściej niż reszta bazy i mają ~20× wyższe blended LTV. Po funkcję sięga więc segment, który zostawia w Localo najwięcej: duże, zaangażowane agencje i specjaliści. Najbardziej wartościowa persona dostała narzędzie, z którego faktycznie korzysta. Nie wiemy czy raporty stworzyły takie konta — nie izolowaliśmy takiego wpływu. Wiemy, że je w narzędziu trzymają. To ",
      para3Bold: "funkcja-kotwica",
      para3Rest: " dla segmentu, na którym firmie bardzo zależy.",
      quotePre: "„Są klienci, którzy ",
      quoteAccent1: "płacą tylko za to",
      quoteMid: ". Ta funkcja rozwiązała problem użytkowników, co ",
      quoteAccent2: "zmniejszyło tarcie i churn",
      quoteEnd: ".”",
      quoteAttribution: "Localo CEO",
    },
    podsumowanie: {
      eyebrow: "09 · PODSUMOWANIE",
      title: "Projekt nie skończył się na wdrożeniu",
      intro: "Przez kolejne tygodnie obserwowaliśmy adaptację do nowej funkcji. Analizowałam nagrania w Clarity, żeby zobaczyć, jak użytkownicy radzą sobie z raportami. Sprawdzałam, czy w ticketach supportu nie pojawiają się zgłoszenia dotyczące tej funkcji. Zbieraliśmy pomysły na kolejne iteracje, część z nich dodaliśmy, m.in. pokazanie statusu czy raport został wysłany bezpośrednio, został wygenerowany link, czy PDF.",
      lessons: [
        { title: "Wiem, że nic nie wiem", text: "Najcenniejsze w tym projekcie nie było samo badanie, tylko to, że zanim cokolwiek zaczęliśmy budować, wypisaliśmy listę rzeczy, których nie wiemy. Hipoteza CEO nie upadła dlatego, że była głupia — była rozsądna. Upadła dlatego, że opierała się na założeniach o ludziach, których nigdy nie pytaliśmy." },
        { title: "Techniczne nie znaczy później", text: "Wciągnięcie developerów na etapie koncepcji, a nie handoffu, zmieniło kształt produktu. Ograniczenia klientów pocztowych nie były detalem implementacyjnym — były czynnikiem, który zdefiniował, jak wygląda raport." },
      ],
      nextProjectLabel: "Zobacz kolejny projekt",
    },
  },
  en: {
    heroEyebrow: "CASE STUDY - LOCALO · CLIENT ACQUISITION",
    heroTitle: "for client acquisition.",
    heroTitleAccent: "One flow",
    heroLead:
      "Lead generation and visibility research existed in Localo separately. Both worked, but almost nobody launched them on their own — the value only reached people on a Customer Success call. On top of that, both ended up in an external CRM or a spreadsheet. I designed Client Acquisition: one tool with two modules that explains itself and closes the loop without leaving the product. After the redesign, median session time on the feature grew from 4.0 to 7.3 minutes, and the number of onboarding calls dropped.",
    metaBar: [
      { label: "PRODUCT", value: "Localo" },
      { label: "SCALE", value: "6,700+ users" },
      { label: "INDUSTRY", value: "Local SEO / B2B SaaS" },
      { label: "USERS", value: "Freelancers, SEO specialists, agencies" },
    ],
    chapters: {
      skrot: "01 Long story short",
      problem: "02 Knowledge",
      discovery: "03 Discovery",
      reframing: "04 Re-framing",
      decyzje: "05 Decisions",
      handoff: "06 Handoff",
      rozwiazanie: "07 Solution",
      wynik: "08 Results",
      podsumowanie: "09 Summary",
    },
    skrot: {
      eyebrow: "01 · CONTEXT, IMPACT & ROLE",
      title: "Long story short",
      introBold: "Localo is a tool for people managing Google Business Profiles",
      introRest:
        " — one or dozens at a time. It automates the work and tells you what to do next: a weekly task list with priorities for every profile, audits in seconds, reports ready to send to a client in minutes.",
      contextPanel: {
        title: "Brief — Client Acquisition",
        text1: "The feature was built as an MVP by a single developer and stayed exactly as it was. Nobody on the team pretended it was good.",
        text2: "“We know the UX and the overall design of this feature is weak — users only understand the tool's value, and how to use it at all, after onboarding with Customer Success on a call. We want users to come in, see the wow effect, and use it on their own.”",
      },
      closingLead: "This wasn't a project where the problem had to be discovered. The problem was known - ",
      closingBold: "the entire job was figuring out how to solve it.",
      statsIntroTitle: "How the metrics changed:",
      stats: [
        { value: "+81%", label: "longer median session on the feature: 4.0 → 7.3 min" },
        { value: "5.5x", label: "more likely to pay than the rest of the base: 28.0% vs 5.1%" },
        { value: "~9x", label: "higher blended LTV for feature users: $149.97 vs $16.31" },
      ],
      statsCaption: "The last two compare feature users against the rest of the base, not a before/after measurement. I break this down in chapter 07.",
      roleOverline: "MY ROLE — DESIGN LEAD, END TO END",
      roleQuote: "At Localo I owned the entire product — from discovery to delivery.",
      roleList: [
        "defined the problems",
        "led research and designed the UI/UX",
        "tested with users and iterated",
        "advised on what made the roadmap and what didn't",
        "grew the design system and maintained it together with engineering",
        "joined client calls, so I wasn't relying on someone else's notes",
        "mentored a junior product designer",
      ],
      scopePanel: {
        title: "Redesign: Research & Sales mode",
        blocks: [
          { label: "MY SCOPE", text: "expert audit of the existing feature, new information architecture, user journey and flow, naming, UI, states and messaging, handoff, design QA." },
          { label: "COLLABORATION", text: "scope and priorities. Engineering team — technical constraints, from day one. Customer Success — insight into what people didn't understand on calls. Plus support from QA and the writer." },
        ],
      },
    },
    problem: {
      eyebrow: "02 · Knowledge gathering",
      title: "The knowledge already lived in the team",
      introPre: "Client Acquisition reached people ",
      introBold: "whose behavior I'd already studied",
      introRest: " on other projects at Localo. So I went in with a ready persona and knowledge of how they work day to day and what they need.",
      persona: {
        overline: "WHO IT'S FOR (PERSONA)",
        quote: "Freelancers, SEO specialists, and people at agencies responsible for client acquisition.",
        commonBold: "What they have in common: ",
        commonText: "they don't come for data — they come for an answer to who should I call tomorrow and what do I show them.",
      },
      sourcesTitle: "Sources of knowledge and key findings",
      sourcesIntro: "The project scope didn't call for fresh discovery or deeper research. I relied on four sources that spoke directly to this feature: my own ",
      sourcesIntroBold: "expert audit, session recordings, support tickets, and Customer Success's knowledge.",
      auditTitle: "Expert audit",
      auditItems: ["Experience", "Nielsen's 10 heuristics", "Guidelines & best practices", "Accessibility"],
      moreSourcesLead: "On top of that, I looked for information in these places:",
      sourceCards: [
        { title: "Session recordings in Clarity", text: "The audit tells you what's broken by the rules. Recordings tell you where people actually stop, what they click, and at what point they close the tab." },
        { title: "Conversations with Customer Success", text: "They'd explained this feature live dozens of times, so they knew things about it that don't show in the interface: exactly what they tell clients, what users struggle with most, and the moment the lightbulb goes on." },
        { title: "Support tickets", text: "I went through the tickets about the feature: a list of frustrations, problems, and requests for help. Questions about credits kept coming back — and that report later became a concrete change in the project." },
        { title: "Session with engineers", text: "I pulled in the engineering team before I sketched anything. I wanted to know how the feature works today and why, what our technical constraints are, what's blocking us, and what we already know we want to drop or move to a different stack." },
      ],
      aiSynthesisTitle: "AI-assisted research synthesis",
      aiSynthesisText: "I combined the Clarity recordings, support conversations, and expert-audit findings using Claude. I wanted to see where the observations overlapped, whether patterns emerged, and which recorded frustrations came up most often.",
      findingsTitle: "Key findings",
      findings: [
        { number: "01", title: "High barrier to entry", text: "Every new user needed manual onboarding from CS. Walking into the tool, they had no idea what they'd get." },
        { number: "02", title: "Results weren't repeatable", text: "The same query could return a different list, with no way back to the previous one — no snapshots, no search history." },
        { number: "03", title: "No continuity", text: "Leads lived in Sales mode, visibility data in Research, with no shared context and no visible link between them." },
        { number: "04", title: "External tools", text: "One task, several exits from the tool. A lead was a row with no data to decide on — no site, review count, or map link, those were still project goals — while contact status and notes lived in someone else's spreadsheet." },
        { number: "05", title: "Invisible cost", text: "No communication of limits. Nowhere did it say how many credits a user had, what an action cost, or what happens when they run out." },
      ],
      scopeTitle: "Scope — what we're doing and what we're not",
      scopeIntro: "Together with the PM and the team, I nailed down exactly what was in scope for the redesign. That included: ",
      scopeIntroBold: "stabilizing list generation, a micro-CRM with lead statuses, a better lead preview, communicating limits, communicating value, naming, and a visible link between both halves of the feature.",
      scopeIntroEnd: " We deliberately excluded three things:",
      scopeOut: [
        { title: "How keywords are added.", text: "We used it in other parts of the app, so changing it here would mean rethinking it everywhere. ", textBold: "That needed a project of its own." },
        { title: "Result history.", text: "It only becomes worth something once people come back to the feature. ", textBold: "First we had to check whether they would." },
        { title: "Buying extra credits.", text: "Bundles, price tiers, one-off billing or added to the subscription — that's a pricing-model decision and ", textBold: "needs a conversation with the business." },
      ],
      scopeClosing1Pre: "That list did two things: ",
      scopeClosing1Bold: "it kept us disciplined",
      scopeClosing1Rest: " — whenever we drifted off with ideas, we came back to the \"agreement,\" which kept us from burying ourselves in one project for six months. It also aligned expectations: the manager knew what the output would be, and the engineers and I knew what we were responsible for.",
      scopeClosing2: "As always, and this time too, I put together a goal that was presented to and approved by the team. That way, at every stage of the project, we remember who it's for and why we're doing it.",
      goalOverline: "GOAL",
      goalPre: "Take the burden of explaining the feature off the team. ",
      goalBold: "Users should walk in, see the result, and keep using it on their own",
      goalRest: " — no call, no instructions, no leaving for outside tools.",
    },
    discovery: {
      eyebrow: "03 · DISCOVERY",
      title: "What we didn't know about our clients' clients.",
      intro1Bold: "eight in-depth interviews",
      intro1Pre: "I had two weeks for discovery and ran it solo. Under those conditions I settled on ",
      intro1Rest:
        " — a mix of agencies and freelancers — to understand the shape of the problem: how they report today and what their clients ask, which tools, words, colours and formats they use, what the client does with the report after receiving it. What interested me most was the language they use to translate results for someone who doesn't know SEO. And who creates reports versus who receives them.",
      intro2Pre: "In parallel I ran a ",
      intro2Bold: "quantitative survey (around 100 responses)",
      intro2Rest:
        " to know what and how often users report. An interview tells you why someone does something. A survey tells you how many people do the same thing. That decided what made it into the report — the default report was meant to be the one nobody has to fix.",
      stats: [
        { value: "8", label: "In-depth interviews" },
        { value: "100+", label: "Survey\nresponses" },
      ],
      intro3Bold: "The third source was the customer success team",
      intro3Rest:
        ". They're close to users and their problems day to day, so besides a meeting we went through tickets together. That's how I know how many of them were about the Localo API — I'll come back to that under key decisions — and the language our users use for their own clients.",
      intro4: "I combined the qualitative and quantitative data into one coherent picture using Claude to speed up this stage of the work. It analysed the quantitative and qualitative research materials and the meeting transcripts for me.",
      findingsTitle: "Key findings",
      findings: [
        { number: "01", title: "Reports are scanned, not analysed", text: "The end client runs their own business and doesn't sit down to analyse numbers. They skim the report." },
        { number: "02", title: "Assembling a report is hours, every month, from scratch", text: "They collected data from several tools and put it together by hand into one presentation. They said outright they'd happily automate it." },
        { number: "03", title: "Need for client education", text: "Reports often came with separate explanations: what the data is and why it matters to the client." },
      ],
      personaTitle: "Our clients' clients — the persona",
      personaIntroBold: "Reports have two audiences.",
      personaIntroRest: " The specialist creates the report and uses it to show the client the work is paying off. The end client only scans it. So I was also designing for someone who isn't a user of our product.",
      personaCards: [
        { title: "Who they are", text: "A non-technical business owner. Doesn't know SEO and doesn't have a Localo account." },
        { title: "What they want", text: "Two answers: \"is it getting better\" and \"what's in it for me\"." },
        { title: "How they read", text: "Skims the report visually. Has neither the time, the skill, nor the will to analyse numbers and charts." },
      ],
    },
    reframing: {
      eyebrow: "04 · RE-FRAMING",
      title: "The problem wasn't access — it was effort",
      text: "The hypothesis we started with didn't hold up in research. The problem wasn't access to the data — it was the effort and commitment that entering the tool would demand from the client. That flipped the direction: instead of letting the client into Localo, we had to push the report out to them.\n\nI presented the CEO with the research findings, the framed problem and the new hypothesis. He accepted them without resistance — the data was unambiguous. We agreed on the project's goal together.",
      shiftTitle: "Change of direction",
      hypothesisRejected: {
        title: "Starting hypothesis",
        status: "Rejected",
        text: "Give the client read-only access to the tool, and they'll check their own data. The problem wasn't access, it was the effort and commitment.",
      },
      hypothesisLive: {
        title: "The real hypothesis",
        status: "New!",
        note: "Test: what share of report users turns on automation, and how many never generate manually at all.",
        text: "If the report builds itself and reaches the client, specialists will switch to auto-reporting and stop creating reports manually.",
      },
      goalLabel: "Build a tool for ",
      goalBold1: "automatic reporting",
      goalMid: " that clearly shows results to non-technical clients and ",
      goalBold2: "builds trust in the collaboration",
      goalEnd: ".",
    },
    decyzje: {
      eyebrow: "05 · KEY DECISIONS & TRADE-OFFS",
      title: "Decisions that shaped the direction",
      mainDecision: {
        title: "Generate from the full dataset, select only before sending the report",
        steps: [
          { label: "Rejected option:", text: "Choosing report elements before generation seemed like the logical flow. Create report → pick a period → choose data → generate." },
          { label: "Reason:", bullets: [
            { text: "every new report generates a rank map, ", bold: "and that costs money" },
            { text: "selecting before generation meant the user would produce a new report every time they changed their mind", bold: "" },
          ] },
          { label: "Effect:", text: "Lower cost on our side and less friction on the user's side. One decision, two wins." },
        ],
      },
      pair: [
        {
          title: "The builder as an\nassistant, not an empty form",
          image: "/raporty-ds-smart-creator.webp",
          text1: "The report generates itself, and the user gets a ready draft. They edit/approve and send. The final word stays with them: the automation prepares, but it ",
          text1Bold: "doesn't decide for them.",
          text2Bold: "Reason:",
          text2: "Designing in line with the company's mission: automating execution, not replacing understanding.",
        },
        {
          title: "We didn't build an API",
          image: "/raporty-ds-api-stop.webp",
          text1: "Users directly asked for an API to build their own reports in their own framework. We didn't go that route: the feature answered a narrow group's need and demanded a lot of development work.",
          text1Bold: "",
          text2Bold: "Effect:",
          text2: "At this stage the effort was disproportionate to the payoff. We logged the idea in the backlog.",
        },
      ],
      builtTitle: "What I built",
      builtText: "Reporting and auto-reporting. The user sets — globally or separately per profile — how often a report should generate. They pick, say, once a month, and every month get a ready document with the profile's key information: keyword rankings and their changes, profile activity, reviews. They can turn individual sections on and off, so the report isn't cluttered with things that don't matter to their client. Add an address, and send.",
      testsTitle: "Usability testing",
      testsText: "I mapped the full report-creation flow, built a clickable prototype in Claude Code to test it with users before involving development and QA. I prepared scenarios to answer 3 questions:",
      testsQuestions: [
        "Are the steps in the report-creation process predictable?",
        "Does the user easily find a specific profile's report in the reports manager, and do they understand the status?",
        "Is the builder (editing the draft and sending) easy to use?",
      ],
      testsFindings: [
        { title: "The list was organised the opposite way from how users work.", text1: "The manager showed every report generated for every profile. Users got lost in that list and had trouble navigating.", text2: "The reason turned out to be fundamental: their daily work is organised per profile, so they think profile → report. My list showed the reverse: report → for profile XYZ. It wasn't a labelling problem, it was a mismatch with their mental model." },
        { title: "Report history wasn't useful.", text1: "The only thing respondents actually looked for was: is the latest report still a draft, or has it already gone to the client.", text2: "" },
      ],
      testsClosing: "In the next round every respondent moved through the feature without hesitation. They handled tasks smoothly — e.g. find the latest report for profile xyz, or generate a report for 4 profiles at once. I'll show the updated versions in the next steps.",
    },
    handoff: {
      eyebrow: "06 · HANDOFF & DEVELOPMENT",
      title: "Handoff is more than passing over mockups",
      introBold: "arranged into flows in Figma",
      introPre: "Engineers got mockups ",
      introMid: ", not loose screens: every state, notification examples, mobile versions, and implementation notes wherever a decision was needed. ",
      introBold2: "Plus a write-up of edge cases",
      introRest: " — what happens when there's no data — design-system tokens, and a clickable prototype, so the whole thing could be walked through before writing the first line of code.",
      intro2Pre: "I stayed ",
      intro2Bold: "in constant contact",
      intro2Rest: " with the developers, so questions got resolved on the spot instead of waiting for review. I checked the build on the test environment and flagged differences from the design. I supported QA in defining what needed checking, and collected fixes after launch.",
      infraTitle: "One feature lost to infrastructure",
      infraText1: "Reports sent by email were meant to include interactive rank maps. Clicking the map would open a link where the client could adjust settings and view the data themselves. The feature was built and didn't ship. We caught it before release: email clients handle links poorly — filters flagged them and test messages landed in spam. We didn't have enough time to work around it, so we cut interactive maps from emailed reports.",
      infraText2: "This was the most frustrating moment of the project. The feature worked and was good — it lost to infrastructure. The good news is that we found out, not the users.",
    },
    rozwiazanie: {
      eyebrow: "07 · SOLUTION",
      title: "How it turned out — a report in one click",
      intro: "Below is the final version of the reporting module and reports manager — the one that shipped to production and that users rely on every day. From a single profile's report list, through the report itself, to managing an entire client portfolio.",
      s1Title: "Reports list — one profile's history",
      s1CardTitle: "The draft is already waiting",
      s1CardText: "The user doesn't start from an empty builder. They open the profile, and the draft for the current period is already there — just review and send. Every report on the list shows its period, generation date and status. This is also where auto-reporting is set up.",
      s2Title: "The report",
      s2Text: "The report starts complete — stats, keywords with rank maps, reviews, content, citations and competitors. Everything for the period, nothing to pick manually. The agency logo at the top, and a short explanation next to each metric.",
      s2Pair: [
        { title: "I tailor it to this specific client", text: "Unchecks whatever they didn't work on this month. The report should answer 'is it getting better', not show everything the system can count." },
        { title: "Auto-reporting", text: "Auto-reports are on by default. The data range — e.g. a month — and generation frequency can be edited anytime." },
      ],
      s3Title: "Manager — a list of profiles, not a list of reports",
      s3CardTitle: "The bird's-eye view",
      s3CardText: "Anyone managing a dozen-plus profiles needs a view of their whole client portfolio. This layout came after usability testing: client first, their report second.",
      s3Pair: [
        { title: "Statuses and schedule", text: "Sees what went to the client and when the next report will generate. Without opening every profile individually." },
        { title: "Multiple reports at once", text: "If they need a report outside the fixed schedule, a bulk action handles it." },
      ],
      s3Triple: [
        { title: "Delivery", text: "Three ways from one screen: auto-send, a login-free link, or a PDF." },
        { title: "Sending by email", text: "The report goes to the client — the client doesn't go to the report." },
        { title: "Sending by email", text: "The report goes to the client — the client doesn't go to the report." },
      ],
      s4Title: "Components and states",
      s4Text: "Every component had to handle every state — empty, generating, sent, error. Notifications, empty states, dropdowns and tags came from the design system I built together with engineering.",
    },
    wynik: {
      eyebrow: "08 · RESULTS & PROOF",
      title: "What the numbers showed",
      heroStat: { value: "11–13%", label: "of active users create a report in a given month — roughly one in nine changed a habit" },
      smallStats: [
        { value: "60%", label: "of users turned on auto-generation" },
        { value: "~11×", label: "more often they pay compared to the rest of the base" },
        { value: "44%", label: "no longer creates a report manually" },
        { value: "~20x", label: "higher blended LTV than the rest of the base" },
      ],
      dataCaption: "Data from October 2025 – June 2026, from Localo's data analyst.",
      whatItMeansTitle: "What's behind these numbers",
      para1: "Over nine months, the share of report creators has held in the 11–13% range. It grew after launch, peaked in December, then settled a little lower — but it held. ",
      para1Bold: "This isn't the curve of a fresh feature, it's a new habit.",
      para2: "44%, meanwhile, isn't adoption, ",
      para2Bold: "it's a habit change",
      para2Rest: ". These people stopped manually doing something they'd always done manually. Auto is the dominant mode here, not an add-on — and to me that's the strongest number on this list.",
      para3: "Report users pay ~11× more often than the rest of the base and have ~20× higher blended LTV. So the feature reaches the segment that leaves the most in Localo: large, engaged agencies and specialists. The most valuable persona got a tool it actually uses. We don't know if reports created those accounts — we didn't isolate that effect. We know they keep them in the tool. It's an ",
      para3Bold: "anchor feature",
      para3Rest: " for the segment the company cares about most.",
      quotePre: "\"Some clients ",
      quoteAccent1: "pay just for this",
      quoteMid: ". This feature solved a real user problem, which ",
      quoteAccent2: "reduced friction and churn",
      quoteEnd: ".\"",
      quoteAttribution: "Localo CEO",
    },
    podsumowanie: {
      eyebrow: "09 · SUMMARY",
      title: "The project didn't end at launch",
      intro: "Over the following weeks we watched how the new feature was adopted. I reviewed Clarity recordings to see how users handled reports. I checked support tickets for anything related to the feature. We gathered ideas for the next iterations and shipped some of them, including showing whether a report was sent directly, a link was generated, or a PDF.",
      lessons: [
        { title: "I know that I know nothing", text: "The most valuable part of this project wasn't the research itself — it was that before we built anything, we wrote down everything we didn't know. The CEO's hypothesis didn't fail because it was foolish — it was reasonable. It failed because it rested on assumptions about people we'd never actually asked." },
        { title: "Technical doesn't mean later", text: "Bringing engineers in at the concept stage, not at handoff, changed the shape of the product. Email client constraints weren't an implementation detail — they were a factor that defined what the report looks like." },
      ],
      nextProjectLabel: "See the next project",
    },
  },
}
