import { TrendingDown, BarChart2, Video, Users, Headphones, Star } from "lucide-react"

export const copy = {
  pl: {
    h1: "Pozyskiwanie klientów.",
    h1Accent: "Jeden flow",
    h1Suffix: " zamiast dwóch osobnych narzędzi.",
    heroEyebrow: "Localo · Client Acquisition",
    intro: "Generowanie leadów i research widoczności istniały w Localo osobno, trudne w obsłudze i wymagające onboardingu. Sales mode dodatkowo zmuszał do pracy w zewnętrznych CRM-ach i arkuszach. Zaprojektowałam ",
    introProduct: "Client Acquisition",
    introSuffix: ": jedno narzędzie z dwoma modułami, spójne i samowyjaśniające się, bez wychodzenia do zewnętrznych aplikacji.",
    roleLabel: "Moja rola",
    roleLead: "Discovery → delivery",
    roleDesc: "— badania użytkowników, hipotezy, architektura flow, ekrany i testy użyteczności. Zespół: PM, QA, copywriter, dev.",
    roleTitle: "Design lead,",
    roleTitleAccent: "od A do Z.",
    chapters: {
      hero: "Start",
      s01: "Efekty",
      s02: "Problem",
      s03: "Proces",
      s04: "Rozwiązanie",
      s05: "Wnioski",
    },
    meta: [
      { label: "Produkt", value: "Localo" },
      { label: "Skala", value: "5 000+ użytkowników" },
      { label: "Branża", value: "Local SEO / B2B SaaS" },
      { label: "Użytkownicy", value: "Agencje SEO i freelancerzy" },
    ],
    s01: {
      h2: "Kluczowe metryki",
      body: <><strong className="text-slate-700">Dwa osobne narzędzia</strong> — Research mode i Sales mode — zostały zastąpione <strong className="text-slate-700">jednym spójnym flow</strong> z dwoma modułami: Leads Finder i Visibility Scans. Użytkownik <strong className="text-slate-700">nie przeskakuje między trybami</strong>: wynik z jednego modułu naturalnie prowadzi do drugiego. Narzędzie jest <strong className="text-slate-700">samowyjaśniające się</strong> i nie wymaga zewnętrznych aplikacji do dokończenia zadania.</>,
      metrics: [
        { num: "9×", caption: "Wyższe blended LTV na użytkowniku funkcji", color: "#0ABA53", icon: "ltv" },
        { num: "+81%", caption: "Dłuższy czas sesji na funkcji", color: "#0ABA53", icon: "time" },
        { num: "+145%", caption: "Więcej sesji na funkcji", color: "#0ABA53", icon: "sessions" },
        { num: "5,5×", caption: "Użytkownicy funkcji płacą częściej", color: "#0ABA53", icon: "pay" },
      ],
      lastPara: <>Funkcja zwiększyła postrzeganą wartość wyższych tierów i obniżyła <strong className="text-slate-700">churn</strong> wśród agencji z wieloma klientami. Zanotowaliśmy wzrost <strong style={{ color: "#0F172A", fontWeight: 800 }}>adopcji funkcji</strong> oraz pośredni wpływ na <strong className="text-slate-700">liczbę zarządzanych profili</strong>, kluczową metrykę przychodu platformy.</>,
    },
    s02: {
      h2: "Kluczowe odkrycia, które ukształtowały finalny projekt",
      findingTitle: "",
      findingTitleAccent: "Próg wejścia",
      findingTitleSuffix: " i ograniczona adopcja.",
      findingLead: "Złożoność funkcji wymusza ręczny onboarding i wypycha użytkowników do narzędzi zewnętrznych.",
      insights: [
        { n: "2", title: "Zewnętrzne narzędzia", desc: "Jedno zadanie, kilka wyjść z narzędzia." },
        { n: "3", title: "Wysoka bariera wejścia", desc: "Każdy nowy użytkownik wymagał onboardingu od CS." },
        { n: "1", title: "Brak ciągłości", desc: "Leady w Sales mode, dane o widoczności w Research, bez wspólnego kontekstu." },
      ],
      methodsLabel: "Metody badawcze",
      methods: [
        { label: "Analiza ścieżek · funnel drop-off", icon: <TrendingDown className="w-3.5 h-3.5" /> },
        { label: "Dane ilościowe", icon: <BarChart2 className="w-3.5 h-3.5" /> },
        { label: "Nagrania sesji (Clarity)", icon: <Video className="w-3.5 h-3.5" /> },
        { label: "Wywiady z użytkownikami", icon: <Users className="w-3.5 h-3.5" /> },
        { label: "Dane z supportu", icon: <Headphones className="w-3.5 h-3.5" /> },
        { label: "Feedback Customer Success", icon: <Star className="w-3.5 h-3.5" /> },
      ],
    },
    s03: {
      h2: "Od eksploracji do finalnego rozwiązania",
      bodyH3: "Zakres projektu",
      body: "Wspólnie z PM i zespołem ustaliliśmy zakres: ujednolicone flow, mini-CRM, Visibility Scans przy leadzie, kontekstowy onboarding. Resztę świadomie wyłączyliśmy, żeby uniknąć scope creepu.",
      scopeCols: [
        { label: "W scope", inScope: true, items: ["System kredytowy", "Komunikacja wartości", "Widoczne połączenie między funkcjami", "Mikro-CRM w narzędziu"] },
        { label: "Poza scope", inScope: false, items: ["Zmiany w sposobie dodawania keywordów", "Historia", "Redesign pozostałych sekcji produktu"] },
      ],
      goalLabel: "Cel",
      goalText: <><strong style={{ fontWeight: 800 }}>Obniżyć barierę wejścia</strong>, wyeliminować zewnętrzne narzędzia i zwiększyć skuteczność prospectingu, tak by użytkownik sam zrozumiał wartość funkcji i <strong style={{ fontWeight: 800 }}>przełożył ją na deale</strong>.</>,
      flowH3: "Architektura flow",
      flowDesc: "Zmapowałam oba istniejące flow, żeby znaleźć miejsca przecięcia i utraty kontekstu. Oba częściowo pokrywały ten sam obszar, ale żadne nie domykało go w całości.",
      synthesisH3: "Synteza badań",
      synthesisDesc: "Połączyłam nagrania z Clarity, rozmowy z supportem i wywiady z użytkownikami, żeby wyłapać powtarzające się pain pointy i oprzeć decyzje o zakresie na danych, nie intuicji.",
      lofiH3: "Wczesne eksploracje układu",
      lofiImages: [
        { img: "/localo-lofi-1.webp", alt: "Prospect finder: lista" },
        { img: "/localo-lofi-2.webp", alt: "Prospect finder: tabela z filtrami" },
        { img: "/localo-lofi-3.webp", alt: "Prospect finder: widok pełny" },
        { img: "/localo-lofi-4.webp", alt: "Business list" },
        { img: "/localo-lofi-5.webp", alt: "Grid research" },
        { img: "/localo-lofi-6.webp", alt: "Ongoing / Archived" },
        { img: "/localo-lofi-7.webp", alt: "Discover new clients: modal" },
        { img: "/localo-lofi-8.webp", alt: "Grid research: pusty stan" },
      ],
    },
    s04: {
      h2: "Jeden flow: od odkrycia do onboardingu",
      intro: "Użytkownik zaczyna od Leads Finder, szuka firm w danej niszy i lokalizacji, buduje listę potencjalnych klientów. Gdy znajdzie interesującego leada, uruchamia Visibility Scan i sprawdza jego widoczność online. Wynik staje się argumentem sprzedażowym i gotowym kontekstem do oferty lub cold maila. Cały proces, od wyszukiwania do aktywacji klienta, dzieje się w jednym miejscu.",
      steps: [
        { step: "01", title: "Lista leadów", desc: "Użytkownik wpisuje kategorię i lokalizację, system zwraca profile Google Business z kluczowymi danymi: brak WWW, liczba opinii, link do map. Kluczowa decyzja: żadnego pustego stanu, wynik natychmiast, bez konfiguracji i onboardingu.", laptopMockup: true, laptopImages: ["/modal.png", "/lead list.png"] },
        { smallCards: [
          { step: "02", title: "Growth Potential", desc: "Jeden scoring zamiast metryk do analizy, kalkulacja zdjęta z użytkownika.", img: "/growth potential.png", imgAlt: "Growth Potential score" },
          { step: "03", title: "Skan widoczności z poziomu leada", desc: "Szybkie sprawdzenie widoczności firmy jako gotowy argument sprzedażowy.", img: "/pin map.png", imgAlt: "Visibility Scan, mapa z pinami" },
        ], bigCard: { step: "04", title: "Zarządzanie statusem leadów", desc: "Mini-CRM wbudowany w produkt. Użytkownik nie musi wychodzić do arkusza.", img: "/status.png", imgAlt: "Status leadów i komentarze" } },
        { step: "05", title: "Pogłębiona analiza", desc: "Kolejne skany widoczności dla dodatkowych słów kluczowych: wynik, keywordy i pozycja na tle konkurencji to gotowy materiał do rozmowy, bez przepisywania.", img: "/localo-analiza.webp", imgAlt: "Pogłębiona analiza", bleedImg: true },
        { step: "06", title: "Onboarding", desc: "Kiedy klient mówi tak, aktywacja profilu następuje jednym kliknięciem, bez wychodzenia z widoku. Pełna pętla: od leada do pierwszego dnia współpracy.", img: "/confirmation.webp", imgAlt: "Aktywacja profilu", height: 480, companionImg: "/mobile.webp", companionImgAlt: "Widok mobilny, generowanie leadów" },
      ],
      rejectedTag: "Odrzucone kierunki",
      rejected: [
        { title: "Osobne tryby Research/Sales", reason: "Wymuszały przełączanie kontekstu." },
        { title: "Surowe metryki zamiast score'u", reason: "Przerzucało na użytkownika obliczenie, czy warto." },
      ],
    },
    s05: {
      h2: "Co bym zrobiła inaczej",
      intro: "",
      items: [
        { title: "Przetestować Growth Potential score wcześniej." },
        { title: "Wcześniej angażować development w projekt." },
        { title: "Więcej czasu przeznaczać na Design QA." },
      ],
    },
  },
  en: {
    h1: "Client Acquisition.",
    h1Accent: "One flow",
    h1Suffix: " instead of two separate tools.",
    heroEyebrow: "Localo · Client Acquisition",
    intro: "Lead generation and visibility research existed in Localo as separate tools, hard to use and requiring onboarding. Sales mode also forced work in external CRMs and spreadsheets. I designed ",
    introProduct: "Client Acquisition",
    introSuffix: ": one tool with two modules, coherent and self-explanatory, without leaving to external apps.",
    roleLabel: "My role",
    roleLead: "Discovery → delivery",
    roleDesc: "— user research, hypotheses, flow architecture, screens, usability tests. Team: PM, QA, copywriter, dev.",
    roleTitle: "Design lead,",
    roleTitleAccent: "end to end.",
    chapters: {
      hero: "Start",
      s01: "Results",
      s02: "Problem",
      s03: "Process",
      s04: "Solution",
      s05: "Takeaways",
    },
    meta: [
      { label: "Product", value: "Localo" },
      { label: "Scale", value: "5,000+ users" },
      { label: "Industry", value: "Local SEO / B2B SaaS" },
      { label: "Users", value: "SEO agencies & freelancers" },
    ],
    s01: {
      h2: "Key metrics",
      body: <><strong className="text-slate-700">Two separate tools</strong> — Research mode and Sales mode — were replaced by <strong className="text-slate-700">one coherent flow</strong> with two modules: Leads Finder and Visibility Scans. The user <strong className="text-slate-700">doesn't jump between modes</strong>: the output of one module naturally leads to the next. The tool is <strong className="text-slate-700">self-explanatory</strong> and doesn't require external apps to complete a task.</>,
      metrics: [
        { num: "9×", caption: "Higher blended LTV per feature user", color: "#0ABA53", icon: "ltv" },
        { num: "+81%", caption: "Longer session time on the feature", color: "#0ABA53", icon: "time" },
        { num: "+145%", caption: "More sessions on the feature", color: "#0ABA53", icon: "sessions" },
        { num: "5.5×", caption: "Feature users pay more often", color: "#0ABA53", icon: "pay" },
      ],
      lastPara: <>The feature increased the perceived value of higher tiers and lowered <strong className="text-slate-700">churn</strong> among agencies with multiple clients. We saw growth in <strong style={{ color: "#0F172A", fontWeight: 800 }}>feature adoption</strong> and an indirect impact on <strong className="text-slate-700">growth in managed profiles</strong>, a key revenue metric for the platform.</>,
    },
    s02: {
      h2: "Key finding that shaped the final design",
      findingTitle: "",
      findingTitleAccent: "Entry barrier",
      findingTitleSuffix: " and limiting adoption.",
      findingLead: "The feature's complexity forces manual onboarding and pushes users to external tools.",
      insights: [
        { n: "2", title: "External tools", desc: "One task, several trips out of the tool." },
        { n: "3", title: "High entry barrier", desc: "Every new user needed onboarding from CS." },
        { n: "1", title: "No continuity", desc: "Leads in Sales mode, visibility data in Research, with no shared context." },
      ],
      methodsLabel: "Research methods",
      methods: [
        { label: "Path analysis · funnel drop-off", icon: <TrendingDown className="w-3.5 h-3.5" /> },
        { label: "Quantitative data", icon: <BarChart2 className="w-3.5 h-3.5" /> },
        { label: "Session recordings (Clarity)", icon: <Video className="w-3.5 h-3.5" /> },
        { label: "User interviews", icon: <Users className="w-3.5 h-3.5" /> },
        { label: "Support data", icon: <Headphones className="w-3.5 h-3.5" /> },
        { label: "Customer Success feedback", icon: <Star className="w-3.5 h-3.5" /> },
      ],
    },
    s03: {
      h2: "From exploration to the final solution",
      bodyH3: "Project scope",
      body: "Together with the PM and team we set the scope: unified flow, mini-CRM, Visibility Scans within a lead, contextual onboarding. Everything else we consciously excluded, to avoid scope creep.",
      scopeCols: [
        { label: "In scope", inScope: true, items: ["Credit system", "Value communication", "Visible connection between features", "Micro-CRM in the tool"] },
        { label: "Out of scope", inScope: false, items: ["Changes to keyword management", "History", "Redesign of other product sections"] },
      ],
      goalLabel: "Goal",
      goalText: <><strong style={{ fontWeight: 800 }}>Lower the entry barrier</strong>, eliminate external tools and increase prospecting effectiveness, so the user understands the feature's value and <strong style={{ fontWeight: 800 }}>translates it into deals</strong>.</>,
      flowH3: "Flow architecture",
      flowDesc: "I mapped both existing flows to find where they intersect and where context gets lost. Both partially covered the same area, but neither closed it completely.",
      synthesisH3: "Research synthesis",
      synthesisDesc: "I combined Clarity recordings, support conversations and user interviews to catch recurring pain points and ground scope decisions in data, not intuition.",
      lofiH3: "Early explorations of the layout",
      lofiImages: [
        { img: "/localo-lofi-1.webp", alt: "Prospect finder: list" },
        { img: "/localo-lofi-2.webp", alt: "Prospect finder: filtered table" },
        { img: "/localo-lofi-3.webp", alt: "Prospect finder: full view" },
        { img: "/localo-lofi-4.webp", alt: "Business list" },
        { img: "/localo-lofi-5.webp", alt: "Grid research" },
        { img: "/localo-lofi-6.webp", alt: "Ongoing / Archived" },
        { img: "/localo-lofi-7.webp", alt: "Discover new clients: modal" },
        { img: "/localo-lofi-8.webp", alt: "Grid research: empty state" },
      ],
    },
    s04: {
      h2: "One flow: from discovery to onboarding",
      intro: "The user starts with Leads Finder, searching for businesses in a given niche and location, building a list of potential clients. When they find an interesting lead, they trigger a Visibility Scan and check the business's online visibility. The result becomes a sales argument and ready context for a proposal or cold email. The entire process, from search to client activation, happens in one place.",
      steps: [
        { step: "01", title: "Leads list", desc: "The user enters a category and location, the system returns Google Business profiles with key data: no website, review count, maps link. Key decision: no empty state, results immediately, no configuration or onboarding.", laptopMockup: true, laptopImages: ["/modal.png", "/lead list.png"] },
        { smallCards: [
          { step: "02", title: "Growth Potential", desc: "One score instead of metrics to analyze, calculation lifted from the user.", img: "/growth potential.png", imgAlt: "Growth Potential score" },
          { step: "03", title: "Visibility scan from the lead", desc: "A quick visibility check as a ready sales argument.", img: "/pin map.png", imgAlt: "Visibility Scan, pin map" },
        ], bigCard: { step: "04", title: "Lead status management", desc: "Mini-CRM built into the product. The user doesn't need to go to a spreadsheet.", img: "/status.png", imgAlt: "Lead status and comments" } },
        { step: "05", title: "In-depth analysis", desc: "Additional visibility scans for more keywords: the result, keywords, and position vs. competition become ready material for a conversation, without copy-pasting.", img: "/localo-analiza.webp", imgAlt: "In-depth analysis", bleedImg: true },
        { step: "06", title: "Onboarding", desc: "When the client says yes, profile activation happens in one click, without leaving the view. The full loop: from lead to day one of cooperation.", img: "/confirmation.webp", imgAlt: "Profile activation", height: 480, companionImg: "/mobile.webp", companionImgAlt: "Mobile view, lead generation" },
      ],
      rejectedTag: "Rejected directions",
      rejected: [
        { title: "Separate Research/Sales modes", reason: "Forced context switching." },
        { title: "Raw metrics instead of a score", reason: "Shifted the is-it-worth-it calculation onto the user." },
      ],
    },
    s05: {
      h2: "What I would do differently",
      intro: "",
      items: [
        { title: "Test the Growth Potential score earlier." },
        { title: "Involve development earlier in the project." },
        { title: "Spend more time on Design QA." },
      ],
    },
  },
}
