import { BarChart2, FileText, Users, TrendingUp } from "lucide-react"

export const copy = {
  pl: {
    h1: "Jak zamienić dane SEO w raporty, które nietechniczni klienci naprawdę czytają",
    intro: "Ten projekt wprowadził ",
    introProduct: "Kreator Raportów",
    introSuffix: " wspierany przez AI — specjalista wybiera okres, AI przygotowuje szkic raportu i podpowiada dane z widocznym trendem, a specjalista tylko edytuje i finalizuje. Raporty upraszczają się do koloru, strzałek trendu i narracji 'było – jest – co się zmieniło', a dostarczyć je można jako link bez logowania albo osadzone bezpośrednio w mailu — wysłane ręcznie lub w pełni automatycznie.",
    roleLabel: "Rola",
    roleText: "Lead product designer — research, architektura informacji, projektowanie interfejsu, testy użyteczności.",
    meta: [
      { label: "Produkt", value: "Localo" },
      { label: "Skala", value: "8 600+ użytkowników" },
      { label: "Branża", value: "Local SEO / B2B SaaS" },
      { label: "Użytkownicy", value: "Specjaliści SEO i agencje" },
    ],
    s01: {
      tag: "01 — Kontekst i wpływ",
      h2: "Specjaliści spędzali godziny na ręcznym składaniu raportów — a potem tłumaczyli telefonicznie to, czego nietechniczny klient i tak nie potrafił wyczytać sam.",
      body: "Dostępne we wszystkich płatnych planach i pakietach (single i multi-listing) — zarówno w widoku pojedynczej wizytówki, jak i na poziomie całego workspace'a, do zarządzania raportowaniem dla całego portfolio profili.",
      metrics: [
        { num: "11%", caption: "Aktywnych twórców raportów miesięcznie — użytkowników MAU tworzy raport co miesiąc, stabilnie od 9 miesięcy (zakres ~11–13%)", color: "#6366F1", icon: "trending" },
        { num: "60%", caption: "Adopcja auto-raportowania — użytkowników włączyło auto-wysyłkę; 44% korzysta wyłącznie z auto, nigdy ręcznie", color: "#6366F1", icon: "chart" },
        { num: "20×", caption: "Łączne LTV vs. reszta bazy — $171,24 vs. $8,60 średniego LTV wszystkich użytkowników", color: "#6366F1", icon: "users" },
      ],
      lastPara: "Użytkownicy raportów płacą też ~11× częściej niż reszta bazy (35,9% vs. 3,3%). To korelacja, nie przyczynowość — raporty (zwłaszcza auto) to domena już zaangażowanych agencji — ale najsilniejszy sygnał wartości zmierzony do tej pory, mocniejszy niż Client Acquisition (28% / $150).",
    },
    s02: {
      tag: "02 — Odkrycia",
      h2: "Co pokazały badania",
      pullQuote: "Klient nie ocenia liczb — patrzy na jedno pytanie: czy jest lepiej, i co mi to daje?",
      insightsH3: "Kluczowe spostrzeżenia",
      insights: [
        { n: 1, title: "Raporty są skanowane, nie analizowane", desc: "Niemal wszyscy respondenci: klienci końcowi są nietechniczni, nie mają czasu ani chęci analizować liczb i wykresów. Raport przeglądany jest wzrokowo — kolor i strzałka wystarczą." },
        { n: 2, title: "Ręczna selekcja danych to codzienne tarcie", desc: "Przed każdą wysyłką specjaliści ręcznie odznaczali zbędne frazy i metryki — ryzykując pominięcie ważnego trendu albo przeciążenie klienta danymi bez znaczenia dla niego." },
        { n: 3, title: "Brak automatyzacji osłabiał zaufanie do współpracy", desc: "Bez cyklicznej, zautomatyzowanej wysyłki raport trafiał do klienta nieregularnie — co zwiększało liczbę pytań o wyniki i obniżało poczucie kontroli nad tym, co się dzieje." },
      ],
      methodsLabel: "Metody badawcze",
      methods: [
        { icon: <Users size={14} />, label: "Wywiady z użytkownikami" },
        { icon: <BarChart2 size={14} />, label: "Dane ilościowe — usage i revenue" },
        { icon: <TrendingUp size={14} />, label: "Analiza konwersji i LTV" },
        { icon: <FileText size={14} />, label: "Ankieta po wdrożeniu" },
      ],
    },
    s03: {
      tag: "03 — Proces",
      h2: "Od eksploracji do finalnego rozwiązania",
      body: "Mapowanie pełnego flow kreatora raportu — od wyboru okresu po finalizację i wysyłkę — jako podstawa do projektowania asystenta AI, który generuje szkic raportu zamiast pustego formularza.",
      scopeCols: [
        { label: "W zakresie",    inScope: true,  items: ["Kreator raportu z AI", "Auto-raportowanie", "Link bez logowania", "Widok workspace"] },
        { label: "Poza zakresem", inScope: false, items: ["Plany wyłącznie publikacyjne", "Integracje zewnętrzne"] },
      ],
      goalLabel: "Cel",
      goalText: "Zamienić ręczny, czasochłonny proces składania raportu w jeden spójny flow — od danych do gotowego raportu dla klienta.",
      flowH3: "User flow — kreator raportu",
      flowDesc: "Wybór okresu → AI sugeruje dane z trendem → specjalista edytuje → finalizacja → wysyłka ręczna lub automatyczna.",
      synthesisH3: "Synteza badań",
      synthesisDesc: "Zestawienie wywiadów ze specjalistami oraz danych ilościowych (usage, konwersja, LTV) w jeden widok — profil nietechnicznego klienta końcowego jako główny punkt odniesienia dla każdej decyzji projektowej.",
      lofiH3: "Wczesne eksploracje",
      lofiDesc: "Jak pokazać wybór danych, trendy i porównania w czasie bez przeciążania specjalisty opcjami. Kluczowa zmiana po testach użyteczności: uproszczenie widoku selekcji fraz i wprowadzenie domyślnych sugestii AI.",
    },
    s04: {
      tag: "04 — Rozwiązanie",
      h2: "Od surowych metryk do historii, którą klient ogarnia w kilka sekund",
      intro: "Raporty dla klientów łączą wybór okresu, sugestie AI, selekcję danych i wysyłkę (ręczną lub automatyczną) w jednym miejscu — bez eksportu do zewnętrznego arkusza.",
      steps: [
        {
          step: "Krok 01",
          title: "Kreator jako inteligentny asystent, nie pusty formularz",
          desc: "AI wybiera dane z widocznym trendem — np. tam gdzie pozycja frazy rośnie — i przygotowuje szkic raportu. Specjalista tylko odznacza zbędne frazy i metryki, dopasowuje zakres i finalizuje.",
          img: "/Sales mode.png",
          imgAlt: "AI suggestions panel",
          reverse: false,
        },
        {
          step: "Krok 02",
          title: "Kolor i strzałka zamiast tabeli liczb",
          desc: "Zielono-czerwona kolorystyka, strzałki trendu i narracja 'było – jest – jaka zmiana' zamiast wykresów do analizy — dopasowane do tego, jak klienci faktycznie czytają raport: pobieżnie, szukając jednej odpowiedzi.",
          img: "/Sales mode.png",
          imgAlt: "Widok raportu dla klienta",
          reverse: true,
        },
        {
          step: "Krok 03",
          title: "Dostarczenie bez logowania — mail lub link, ręcznie lub automatycznie",
          desc: "Auto-raportowanie (60% adopcji, 44% wyłącznie auto) wysyła raport cyklicznie prosto do skrzynki klienta i specjalisty. Alternatywnie: link bez konieczności logowania, do wysłania w dowolnym momencie.",
          img: "/Sales mode.png",
          imgAlt: "Mail i link bez logowania",
          reverse: false,
        },
      ],
      rejectedTag: "Odrzucone kierunki",
      rejected: [
        { title: "Wymóg logowania klienta do obejrzenia raportu", reason: "dodatkowe tarcie dla odbiorcy, który i tak chce tylko rzucić okiem, nie zalogować się do narzędzia specjalisty." },
        { title: "Wykresy i surowe metryki jako domyślna forma prezentacji", reason: "klienci nietechniczni ich nie czytali; potrzebna była narracja 'było – jest', nie dane do analizy." },
        { title: "Ręczny wybór wszystkich danych bez sugestii AI", reason: "zbyt czasochłonne przy każdej wysyłce, realnie prowadziło do rzadszego raportowania lub powrotu do arkusza." },
      ],
    },
    s05: {
      tag: "05 — Wnioski",
      h2: "Czego się nauczyłam",
      intro: "",
      items: [
        { title: "Auto-raportowanie jako domyślny tryb, nie dodatek", desc: "Auto okazało się dominującym trybem — 44% userów nigdy nie tworzy raportu ręcznie. Priorytetyzowałabym automatyzację od startu, nie jako iterację numer dwa." },
        { title: "Korelacja nie równa się przyczynowość", desc: "Silna korelacja z LTV i konwersją (~11× / ~20×) to nie dowód przyczynowości — to głównie już zaangażowane agencje. Przydałby się eksperyment lub kohorta kontrolna, żeby oddzielić efekt raportów od efektu selekcji." },
        { title: "[Twoja trzecia obserwacja]", desc: "[Uzupełnij]." },
      ],
    },
  },
  en: {
    h1: "Turning SEO data into reports that non-technical clients actually read",
    intro: "This project introduced the ",
    introProduct: "Report Builder",
    introSuffix: " powered by AI — the specialist selects a period, AI prepares a draft report and suggests data with visible trends, and the specialist just edits and finalises. Reports are simplified to colours, trend arrows and a 'before – after – what changed' narrative, delivered as a login-free link or embedded directly in an email — sent manually or fully automatically.",
    roleLabel: "Role",
    roleText: "Lead product designer — research, information architecture, UI design, usability testing.",
    meta: [
      { label: "Product", value: "Localo" },
      { label: "Scale", value: "8,600+ affected users" },
      { label: "Industry", value: "Local SEO / B2B SaaS" },
      { label: "Users", value: "SEO specialists & agencies" },
    ],
    s01: {
      tag: "01 — Context & Impact",
      h2: "Specialists spent hours manually compiling reports — then explained by phone what the non-technical client couldn't read anyway.",
      body: "Available on all paid plans and packages (single and multi-listing) — both in single listing view and at workspace level for managing reporting across an entire profile portfolio.",
      metrics: [
        { num: "11%", caption: "Active report creators per month — of MAU users create a report monthly, stable for 9 months (range ~11–13%)", color: "#6366F1", icon: "trending" },
        { num: "60%", caption: "Auto-reporting adoption — of report users enabled auto-send; 44% use only auto, never manual", color: "#6366F1", icon: "chart" },
        { num: "20×", caption: "Total LTV vs. rest of base — $171.24 vs. $8.60 average LTV of all users", color: "#6366F1", icon: "users" },
      ],
      lastPara: "Report users also pay ~11× more often than the rest of the base (35.9% vs. 3.3%). This is correlation, not causation — reports (especially auto) are the domain of already-engaged agencies — but the strongest value signal measured so far, stronger than Client Acquisition (28% / $150).",
    },
    s02: {
      tag: "02 — Discovery",
      h2: "What the research showed",
      pullQuote: "The client doesn't evaluate numbers — they look for one answer: is it better, and what does that mean for me?",
      insightsH3: "Key insights",
      insights: [
        { n: 1, title: "Reports are scanned, not analysed", desc: "Nearly all respondents: end clients are non-technical, they don't have the time or inclination to analyse numbers and charts. Reports are reviewed visually — colour and an arrow are enough." },
        { n: 2, title: "Manual data selection is daily friction", desc: "Before every send, specialists manually unchecked redundant phrases and metrics — risking missing an important trend or overwhelming the client with data irrelevant to them." },
        { n: 3, title: "Lack of automation eroded trust in the collaboration", desc: "Without a cyclical, automated send, reports reached the client irregularly — which increased questions about results and reduced their sense of control over what was happening." },
      ],
      methodsLabel: "Research methods",
      methods: [
        { icon: <Users size={14} />, label: "User interviews" },
        { icon: <BarChart2 size={14} />, label: "Quantitative data — usage & revenue" },
        { icon: <TrendingUp size={14} />, label: "Conversion & LTV analysis" },
        { icon: <FileText size={14} />, label: "Post-launch survey" },
      ],
    },
    s03: {
      tag: "03 — Process",
      h2: "From exploration to final solution",
      body: "Mapping the full report builder flow — from period selection to finalisation and sending — as a basis for designing an AI assistant that generates a report draft instead of an empty form.",
      scopeCols: [
        { label: "In scope",     inScope: true,  items: ["AI report builder", "Auto-reporting", "Login-free link", "Workspace view"] },
        { label: "Out of scope", inScope: false, items: ["Publish-only plans", "External integrations"] },
      ],
      goalLabel: "Goal",
      goalText: "Turn the manual, time-consuming report-building process into one cohesive flow — from data to a finished client report.",
      flowH3: "User flow — report builder",
      flowDesc: "Select period → AI suggests trending data → specialist edits → finalise → send manually or automatically.",
      synthesisH3: "Research synthesis",
      synthesisDesc: "Combining specialist interviews with quantitative data (usage, conversion, LTV) into one view — the profile of the non-technical end client as the main reference point for every design decision.",
      lofiH3: "Early explorations",
      lofiDesc: "How to show data selection, trends and time comparisons without overwhelming the specialist with options. Key change after usability tests: simplifying the phrase selection view and introducing default AI suggestions.",
    },
    s04: {
      tag: "04 — Solution",
      h2: "From raw metrics to a story the client grasps in seconds",
      intro: "Client Reports combines period selection, AI suggestions, data selection and sending (manual or automatic) in one place — no export to an external spreadsheet.",
      steps: [
        {
          step: "Step 01",
          title: "Builder as an intelligent assistant, not an empty form",
          desc: "AI selects data with visible trends — e.g. where a phrase position is growing — and prepares a report draft. The specialist just unchecks redundant phrases and metrics, adjusts scope and finalises.",
          img: "/Sales mode.png",
          imgAlt: "AI suggestions panel",
          reverse: false,
        },
        {
          step: "Step 02",
          title: "Colour and arrow instead of a table of numbers",
          desc: "Green-red colour coding, trend arrows and a 'before – after – what changed' narrative instead of charts to analyse — matched to how clients actually read a report: briefly, looking for one answer.",
          img: "/Sales mode.png",
          imgAlt: "Client report view",
          reverse: true,
        },
        {
          step: "Step 03",
          title: "Delivery without login — email or link, manually or automatically",
          desc: "Auto-reporting (60% adoption, 44% exclusively auto) sends the report cyclically straight to the client's and specialist's inbox. Alternatively: a login-free link to send at any moment.",
          img: "/Sales mode.png",
          imgAlt: "Email and login-free link",
          reverse: false,
        },
      ],
      rejectedTag: "Rejected directions",
      rejected: [
        { title: "Requiring the client to log in to view the report", reason: "extra friction for a recipient who just wants a quick look, not to log into the specialist's tool." },
        { title: "Charts and raw metrics as the default presentation format", reason: "non-technical clients didn't read them; a 'before – after' narrative was needed, not data to analyse." },
        { title: "Manual selection of all data without AI suggestions", reason: "too time-consuming per send, in practice led to less frequent reporting or returning to a spreadsheet." },
      ],
    },
    s05: {
      tag: "05 — Learnings",
      h2: "What I learned",
      intro: "",
      items: [
        { title: "Auto-reporting as the default mode, not an add-on", desc: "Auto turned out to be the dominant mode — 44% of users never create a report manually. I would prioritise automation from the start, not as iteration number two." },
        { title: "Correlation does not equal causation", desc: "The strong correlation with LTV and conversion (~11× / ~20×) is not proof of causation — it's mainly already-engaged agencies. An experiment or control cohort would be needed to separate the report effect from selection effect." },
        { title: "[Your third observation]", desc: "[Fill in]." },
      ],
    },
  },
}
