import { projectTags } from "@/data/projectTags"

export const copy = {
  pl: {
    heroEyebrow: "CASE STUDY · LOCALO",
    heroTitle: "Automatyczny kreator raportów",
    heroTags: projectTags.raporty,
    heroLead:
      "Obaliłam pierwszą hipotezę, przeprowadziłam badania z których utworzyłam nową. Zamiast wpuszczać klienta agencji do Localo, zaprojektowałam raport, który sam się generuje i wysyła jednym kliknięciem. Dziś 60% użytkowników raportów wykorzystuje auto-generowanie zamiast robić to ręcznie.",
    metaBar: [
      { label: "MOJA ROLA", value: "Senior Product Designer" },
      { label: "PRODUKT", value: "Localo" },
      { label: "SKALA", value: "6 700+ użytkowników" },
      { label: "ADOPCJA", value: "11–13%" },
    ],
    chapters: {
      kontekst: "01 Kontekst",
      discovery: "02 Discovery",
      reframing: "03 Re-framing",
      rozwiazanie: "04 Rozwiązanie",
      decyzje: "05 Decyzje",
      wynik: "06 Wynik",
      podsumowanie: "07 Podsumowanie",
    },
    kontekst: {
      eyebrow: "01 · KONTEKST",
      title: "CEO przyszedł z gotowym rozwiązaniem.",
      introPre: "Propozycja CEO odpowiadała na to wprost: ",
      introBold: "dajmy użytkownikom możliwość zapraszania klientów do Localo.",
      introRest:
        " Klient agencji loguje się i sprawdza dane, specjaliści przestają tracić czas na raportowanie. Skoro problemem jest ręczne przygotowywanie raportu, usuńmy raport z równania i wpuśćmy klienta do narzędzia.",
      problemLabel: "PROBLEM",
      problemStatement: "Specjaliści SEO muszą regularnie dowodzić klientom, że ich praca działa. Składają te podsumowania ",
      problemStatementBold1: "ręcznie",
      problemStatementMid1: ", osobno per profil, ",
      problemStatementBold2: "kilka godzin miesięcznie",
      problemStatementMid2: ". Klient jest ",
      problemStatementBold3: "nietechniczny",
      problemStatementRest: " i nigdy wcześniej nie logował się do naszego narzędzia.",
    },
    discovery: {
      eyebrow: "02 · DISCOVERY",
      title: "Badania - Dużo pytań, mało odpowiedzi",
      introLead: "Przekonałam CEO, że to moment, w którym warto zainwestować czas w pogłębienie problemu: ",
      introBold: "dwa czy trzy miesiące pracy nad źle postawioną diagnozą kosztują firmę znacznie więcej niż sprint na dodatkowe badania.",
      stats: [
        { value: "8", label: "Wywiadów pogłębionych" },
        { value: "100+", label: "Odpowiedzi\nz ankiet" },
        { value: "3", label: "Rozmowy z Customer success" },
      ],
      aiPre: "Połączyłam wyniki badań w spójny obraz używając ",
      aiBold1: "AI",
      aiMid: " aby przyspieszyć ten etap pracy. ",
      aiBold2: "Claude",
      aiRest: " przeanalizował dla mnie materiały z badań ilościowych, jakościowych oraz transkrypty ze spotkań.",
      findingsTitle: "Kluczowe odkrycia",
      findings: [
        { number: "01", title: "Raport jest skanowany", text: "Klient końcowy prowadzi własną firmę i nie siada do analizy liczb. Przelatuje raport wzrokiem." },
        { number: "02", title: "Składanie raportu to godziny, co miesiąc", text: "Zbierali dane z kilku narzędzi i składali je ręcznie w jedną prezentację." },
        { number: "03", title: "Potrzeba edukacji klienta", text: "Do raportów często dołączano osobne wyjaśnienia: czym są dane i dlaczego mają znaczenie dla klienta." },
      ],
      personaTitle: "Klienci naszych klientów - Persona",
      personaIntroBold: "Raporty mają dwóch odbiorców.",
      personaIntroRest: " Specjalista tworzy raport i pokazuje nim klientowi, że praca przynosi efekty. Klient końcowy tylko go skanuje. Projektowałam więc także dla kogoś, kto nie jest użytkownikiem naszego produktu.",
      personaCards: [
        { title: "Kim jest", text: "Nietechniczny właściciel firmy. Nie zna się na SEO i nie ma konta w Localo." },
        { title: "Czego chce", text: "Dwóch odpowiedzi: „czy jest lepiej” i „co mi to daje”." },
        { title: "Jak czyta", text: "Przelatuje raport wzrokiem. Nie ma czasu, umiejętności ani chęci, żeby analizować liczby i wykresy." },
      ],
    },
    reframing: {
      eyebrow: "03 · RE-FRAMING",
      title: "Zmiana kierunku",
      text: "Hipoteza, z którą zaczynaliśmy, nie obroniła się w badaniach. Problemem nie był dostęp do danych — tylko wysiłek i zaangażowanie, których wejście do narzędzia wymagałoby od klienta. To odwróciło kierunek: zamiast wpuszczać klienta do Localo, trzeba było wypchnąć raport do niego.\n\nPrzedstawiłam CEO wyniki badań, sformułowany problem i nową hipotezę. Przyjął je bez oporu — dane były jednoznaczne. Cel projektu ustaliliśmy wspólnie.",
      hypothesisRejected: {
        title: "Hipoteza na starcie",
        status: "Obalona",
        text: "Wpuśćmy klienta do narzędzia w trybie tylko do odczytu, a sam sprawdzi swoje dane.\nProblemem nie był dostęp, tylko wysiłek i zaangażowanie.",
      },
      hypothesisLive: {
        title: "Hipoteza właściwa",
        status: "New!",
        note: "Sprawdzian: jaki udział użytkowników raportów włącza automat i jaka część z nich nie generuje ręcznie w ogóle.",
        text: "Jeśli raport będzie powstawał sam i trafiał do klienta, specjaliści przejdą na autoraportowanie i przestaną tworzyć raporty ręcznie.",
      },
      goalLabel: "Zbudować narzędzie do ",
      goalBold1: "automatycznego raportowania",
      goalMid: ", które jasno pokazuje wyniki nietechnicznym klientom i ",
      goalBold2: "buduje zaufanie do współpracy",
      goalEnd: ".",
    },
    rozwiazanie: {
      eyebrow: "04 · ROZWIĄZANIE",
      title: "Co zbudowałam",
      intro: "Raportowanie i autoraportowanie. Użytkownik ustawia – globalnie albo osobno dla konkretnej wizytówki – jak często ma się generować raport. Dostaje gotowy dokument z najważniejszymi informacjami o wizytówce: pozycjami słów kluczowych i ich zmianami, aktywnością na profilu, opiniami. Może włączać i wyłączać poszczególne sekcje, w zależności od potrzeb swoich klientów.",
      s1CardTitle: "Lista raportów – historia jednej wizytówki",
      s1CardText: "Użytkownik nie zaczyna od pustego kreatora. Otwiera wizytówkę, a draft za bieżący okres już tam jest – zostaje przejrzeć i wysłać.",
      s2Title: "Raport",
      s2Text: "Raport startuje kompletny – statystyki, frazy z mapami pozycji, opinie, treści, cytowania i konkurencja. Wszystko z okresu, nic nie trzeba dobierać. Logo agencji na górze, a przy metrykach krótkie wyjaśnienie, co znaczą.",
      s2Pair: [
        { title: "Dopasowuję do konkretnego klienta", text: "Odznacza to, nad czym w tym miesiącu nie pracował. Raport ma odpowiadać na „czy jest lepiej”, a nie pokazywać wszystko, co system umie policzyć." },
        { title: "Auto-raportowanie", text: "Auto-raporty włączone są domyślnie. Można edytować zakres danych – np. miesiąc – i częstotliwość generowania w dowolnym momencie." },
      ],
      s3Title: "Manager – lista wizytówek, nie lista raportów",
      s3CardTitle: "Widok z lotu ptaka",
      s3CardText: "Kto ma pod sobą kilkanaście wizytówek, potrzebuje widoku na całe portfolio klientów. To układ po testach użyteczności: najpierw klient, potem jego raport.",
      s3Pair: [
        { title: "Statusy i harmonogram", text: "Widzi, co poszło do klienta i kiedy wygeneruje się następny raport. Bez wchodzenia w każdą wizytówkę osobno." },
        { title: "Wiele raportów na raz", text: "Jeśli potrzebuje raportu poza stałym harmonogramem, zrobi to akcją zbiorczą." },
      ],
      s3Triple: [
        { title: "Wysyłka", text: "Trzema sposobami z jednego ekranu: auto-wysyłka, link bez logowania lub PDF." },
        { title: "Wysyłka mailem", text: "Raport idzie do klienta – klient nie idzie do raportu." },
        { title: "Wysyłam mailem", text: "Raport idzie do klienta – klient nie idzie do raportu." },
      ],
    },
    decyzje: {
      eyebrow: "05 · Decyzje projektowe",
      title: "Kluczowe decyzje",
      mainDecision: {
        title: "Raport generowany jest z pełnych danych, selekcja następuje przed wysyłką",
        bullets: [
          { text: "każdy nowy raport generuje mapę pozycji, ", bold: "a to kosztuje", rest: "," },
          { text: "przy wyborze przed generowaniem użytkownik produkowałby nowy raport przy każdej zmianie zdania.", bold: "", rest: "" },
        ],
      },
      pair: [
        {
          title: "Kreator jako asystent, nie pusty formularz",
          image: "/raporty-ds-smart-creator.webp",
          text: "Raport generuje się sam, a użytkownik dostaje gotowy draft. Automat przygotowuje, ale ",
          textBold: "nie decyduje za niego.",
          textRest: "",
        },
        {
          title: "Nie zbudowaliśmy API",
          image: "/raporty-ds-api-stop.webp",
          text: "Na obecnym etapie nakład pracy był ",
          textBold: "nieproporcjonalny do zysku.",
          textRest: " Zapisaliśmy ten pomysł do backlogu.",
        },
      ],
      testsTitle: "Zmiany po testach użyteczności",
      testsFindings: [
        { title: "Lista była zorganizowana odwrotnie niż praca użytkownika.", text: "Manager pokazywał wszystkie raporty wygenerowane dla wszystkich wizytówek. Użytkownicy gubili się na tej liście i mieli problem z nawigacją." },
        { title: "Historia raportów była nieprzydatna.", text: "Respondenci szukali informacji czy najnowszy raport jest jeszcze szkicem, czy poszedł już do klienta." },
      ],
      infraTitle: "Interaktywne mapy przegrały z infrastrukturą",
      infraText: "W raportach wysyłanych mailem miały być interaktywne mapy pozycji – kliknięcie w mapę otwierałoby link. Klienty pocztowe jednak filtrowały wiadomości testowe jako spam. Nie mieliśmy dość czasu, żeby to obejść, więc wycięliśmy mapy z raportów wysyłanych mailem. Dobra wiadomość jest taka, że dowiedzieliśmy się o tym my, a nie użytkownicy.",
    },
    wynik: {
      eyebrow: "06 · WYNIK I DOWODY",
      title: "Zmiana nawyku",
      intro: "Co 9 użytkownik raportów przestał robić ręcznie coś, co robili ręcznie od zawsze. Auto jest tu trybem dominującym, nie dodatkiem.",
      heroStat: { value: "11–13%", label: "aktywnych użytkowników tworzy raport w danym miesiącu — mniej więcej jeden na dziewięciu zmienił nawyk" },
      smallStats: [
        { value: "44%", label: "nie tworzy już raportu ręcznie" },
        { value: "~20x", label: "wyższe blended LTV niż reszta bazy" },
      ],
      dataCaption: "Dane z okresu październik 2025 – czerwiec 2026, od analityka danych w Localo.",
    },
    podsumowanie: {
      eyebrow: "07 · Podsumowanie",
      title: "Wnioski",
      intro: "Przez kolejne tygodnie obserwowaliśmy adaptację do nowej funkcji. Analizowałam nagrania w Clarity, żeby zobaczyć, jak użytkownicy radzą sobie z raportami. Sprawdzałam, czy w ticketach supportu nie pojawiają się zgłoszenia dotyczące tej funkcji. Zbieraliśmy pomysły na kolejne iteracje, część z nich dodaliśmy, m.in. pokazanie statusu czy raport został wysłany bezpośrednio, został wygenerowany link, czy PDF.",
      lessons: [
        { title: "Wiem, że nic nie wiem", text: "Najcenniejsze w tym projekcie było to, że wypisaliśmy listę rzeczy, których nie wiemy. Hipoteza CEO upadła dlatego, że opierała się na założeniach o ludziach, których nigdy nie pytaliśmy." },
        { title: "Techniczne nie znaczy później", text: "Wciągnięcie developerów na etapie koncepcji, a nie handoffu, zmieniło kształt produktu. Ograniczenia klientów pocztowych nie były detalem implementacyjnym — były czynnikiem, który zdefiniował, jak wygląda raport." },
      ],
    },
  },
  en: {
    heroEyebrow: "CASE STUDY · LOCALO",
    heroTitle: "Automatic report builder",
    heroTags: projectTags.raporty,
    heroLead:
      "I disproved the first hypothesis, ran the research and built a new one out of it. Instead of letting the agency's client into Localo, I designed a report that generates and sends itself with one click. Today 60% of report users rely on auto-generation instead of doing it by hand.",
    metaBar: [
      { label: "MY ROLE", value: "Senior Product Designer" },
      { label: "PRODUCT", value: "Localo" },
      { label: "SCALE", value: "6,700+ users" },
      { label: "ADOPTION", value: "11–13%" },
    ],
    chapters: {
      kontekst: "01 Context",
      discovery: "02 Discovery",
      reframing: "03 Re-framing",
      rozwiazanie: "04 Solution",
      decyzje: "05 Decisions",
      wynik: "06 Results",
      podsumowanie: "07 Summary",
    },
    kontekst: {
      eyebrow: "01 · CONTEXT",
      title: "The CEO came in with a ready-made solution.",
      introPre: "The CEO's proposal answered that directly: ",
      introBold: "let users invite their clients into Localo.",
      introRest:
        " The agency's client logs in and checks the data, specialists stop wasting time on reporting. If the problem is assembling the report by hand, remove the report from the equation and let the client into the tool.",
      problemLabel: "PROBLEM",
      problemStatement: "SEO specialists have to regularly prove to clients that their work is paying off. They put these summaries together ",
      problemStatementBold1: "by hand",
      problemStatementMid1: ", separately per profile, ",
      problemStatementBold2: "a few hours every month",
      problemStatementMid2: ". The client is ",
      problemStatementBold3: "non-technical",
      problemStatementRest: " and has never logged into our tool before.",
    },
    discovery: {
      eyebrow: "02 · DISCOVERY",
      title: "Research - plenty of questions, few answers",
      introLead: "I convinced the CEO that this was the moment to invest time in deepening the problem: ",
      introBold: "two or three months of work on a wrongly framed diagnosis costs the company far more than a sprint of extra research.",
      stats: [
        { value: "8", label: "In-depth interviews" },
        { value: "100+", label: "Survey\nresponses" },
        { value: "3", label: "Customer success sessions" },
      ],
      aiPre: "I combined the research findings into one coherent picture using ",
      aiBold1: "AI",
      aiMid: " to speed up this stage of the work. ",
      aiBold2: "Claude",
      aiRest: " analysed the quantitative and qualitative research materials and the meeting transcripts for me.",
      findingsTitle: "Key findings",
      findings: [
        { number: "01", title: "Reports are scanned", text: "The end client runs their own business and doesn't sit down to analyse numbers. They skim the report." },
        { number: "02", title: "Assembling a report is hours, every month", text: "They collected data from several tools and put it together by hand into one presentation." },
        { number: "03", title: "Need for client education", text: "Reports often came with separate explanations: what the data is and why it matters to the client." },
      ],
      personaTitle: "Our clients' clients - the persona",
      personaIntroBold: "Reports have two audiences.",
      personaIntroRest: " The specialist creates the report and uses it to show the client the work is paying off. The end client only scans it. So I was also designing for someone who isn't a user of our product.",
      personaCards: [
        { title: "Who they are", text: "A non-technical business owner. Doesn't know SEO and doesn't have a Localo account." },
        { title: "What they want", text: "Two answers: \"is it getting better\" and \"what's in it for me\"." },
        { title: "How they read", text: "Skims the report visually. Has neither the time, the skill, nor the will to analyse numbers and charts." },
      ],
    },
    reframing: {
      eyebrow: "03 · RE-FRAMING",
      title: "Change of direction",
      text: "The hypothesis we started with didn't hold up in research. The problem wasn't access to the data — it was the effort and commitment that entering the tool would demand from the client. That flipped the direction: instead of letting the client into Localo, we had to push the report out to them.\n\nI presented the CEO with the research findings, the framed problem and the new hypothesis. He accepted them without resistance — the data was unambiguous. We agreed on the project's goal together.",
      hypothesisRejected: {
        title: "Starting hypothesis",
        status: "Rejected",
        text: "Give the client read-only access to the tool, and they'll check their own data.\nThe problem wasn't access, it was the effort and commitment.",
      },
      hypothesisLive: {
        title: "The real hypothesis",
        status: "New!",
        note: "Test: what share of report users turns on automation, and how many never generate manually at all.",
        text: "If the report builds itself and reaches the client, specialists will switch to auto-reporting and stop creating reports manually.",
      },
      goalLabel: "Build a tool for ",
      goalBold1: "automatic reporting",
      goalMid: " that clearly shows results to non-technical clients and ",
      goalBold2: "builds trust in the collaboration",
      goalEnd: ".",
    },
    rozwiazanie: {
      eyebrow: "04 · SOLUTION",
      title: "What I built",
      intro: "Reporting and auto-reporting. The user sets – globally or separately per profile – how often a report should generate. They get a ready document with the profile's key information: keyword rankings and their changes, profile activity, reviews. They can turn individual sections on and off, depending on what their clients need.",
      s1CardTitle: "Reports list – one profile's history",
      s1CardText: "The user doesn't start from an empty builder. They open the profile, and the draft for the current period is already there – just review and send.",
      s2Title: "The report",
      s2Text: "The report starts complete – stats, keywords with rank maps, reviews, content, citations and competitors. Everything for the period, nothing to pick manually. The agency logo at the top, and a short explanation next to each metric.",
      s2Pair: [
        { title: "I tailor it to this specific client", text: "Unchecks whatever they didn't work on this month. The report should answer 'is it getting better', not show everything the system can count." },
        { title: "Auto-reporting", text: "Auto-reports are on by default. The data range – e.g. a month – and generation frequency can be edited anytime." },
      ],
      s3Title: "Manager – a list of profiles, not a list of reports",
      s3CardTitle: "The bird's-eye view",
      s3CardText: "Anyone managing a dozen-plus profiles needs a view of their whole client portfolio. This layout came after usability testing: client first, their report second.",
      s3Pair: [
        { title: "Statuses and schedule", text: "Sees what went to the client and when the next report will generate. Without opening every profile individually." },
        { title: "Multiple reports at once", text: "If they need a report outside the fixed schedule, a bulk action handles it." },
      ],
      s3Triple: [
        { title: "Delivery", text: "Three ways from one screen: auto-send, a login-free link, or a PDF." },
        { title: "Sending by email", text: "The report goes to the client – the client doesn't go to the report." },
        { title: "Sending by email", text: "The report goes to the client – the client doesn't go to the report." },
      ],
    },
    decyzje: {
      eyebrow: "05 · Design decisions",
      title: "Key decisions",
      mainDecision: {
        title: "The report is generated from the full dataset, selection happens before sending",
        bullets: [
          { text: "every new report generates a rank map, ", bold: "and that costs money", rest: "," },
          { text: "selecting before generation meant the user would produce a new report every time they changed their mind.", bold: "", rest: "" },
        ],
      },
      pair: [
        {
          title: "The builder as an assistant, not an empty form",
          image: "/raporty-ds-smart-creator.webp",
          text: "The report generates itself, and the user gets a ready draft. The automation prepares, but it ",
          textBold: "doesn't decide for them.",
          textRest: "",
        },
        {
          title: "We didn't build an API",
          image: "/raporty-ds-api-stop.webp",
          text: "At this stage the effort was ",
          textBold: "disproportionate to the payoff.",
          textRest: " We logged the idea in the backlog.",
        },
      ],
      testsTitle: "Changes after usability testing",
      testsFindings: [
        { title: "The list was organised the opposite way from how users work.", text: "The manager showed every report generated for every profile. Users got lost in that list and had trouble navigating." },
        { title: "Report history wasn't useful.", text: "Respondents were looking for one thing: whether the latest report is still a draft, or has already gone to the client." },
      ],
      infraTitle: "Interactive maps lost to infrastructure",
      infraText: "Reports sent by email were meant to include interactive rank maps – clicking a map would open a link. Email clients, however, filtered the test messages as spam. We didn't have enough time to work around it, so we cut the maps from emailed reports. The good news is that we found out, not the users.",
    },
    wynik: {
      eyebrow: "06 · RESULTS & PROOF",
      title: "A habit change",
      intro: "One in nine report users stopped doing by hand something they had always done by hand. Auto is the dominant mode here, not an add-on.",
      heroStat: { value: "11–13%", label: "of active users create a report in a given month — roughly one in nine changed a habit" },
      smallStats: [
        { value: "44%", label: "no longer creates a report manually" },
        { value: "~20x", label: "higher blended LTV than the rest of the base" },
      ],
      dataCaption: "Data from October 2025 – June 2026, from Localo's data analyst.",
    },
    podsumowanie: {
      eyebrow: "07 · Summary",
      title: "Takeaways",
      intro: "Over the following weeks we watched how the new feature was adopted. I reviewed Clarity recordings to see how users handled reports. I checked support tickets for anything related to the feature. We gathered ideas for the next iterations and shipped some of them, including showing whether a report was sent directly, a link was generated, or a PDF.",
      lessons: [
        { title: "I know that I know nothing", text: "The most valuable part of this project was writing down the list of things we didn't know. The CEO's hypothesis failed because it rested on assumptions about people we'd never actually asked." },
        { title: "Technical doesn't mean later", text: "Bringing engineers in at the concept stage, not at handoff, changed the shape of the product. Email client constraints weren't an implementation detail — they were a factor that defined what the report looks like." },
      ],
    },
  },
}
